<div class="w auto">
    <!-- 公共面包屑开始 -->
    <div class="crumbs-nav"><a href="#">首页</a>
      <em>></em><a href="#">订单中心</a>
      <em>></em><a href="#">我的预约</a>
    </div>
    <!-- 公共面包屑结束 -->
    <!-- 主体部分开始 -->
    <div class="content ovh">
      <!-- 侧边栏导航开始 -->
      <div class="side fl dib">
        <h2 class="tit">订单中心</h2>
        <ul>
          <li class="cur"><a href="#" class="tdn">我的预约</a>
          </li>
          <li><a href="#" class="tdn">我的订单</a>
          </li>
          <li><a href="#" class="tdn">收货地址</a>
          </li>
          <li><a href="#" class="tdn">售后服务</a>
          </li>
        </ul>
      </div>
      <!-- 侧边栏导航结束 -->
      <!-- 正文部分开始 -->
      <div class="main fl dib">
        <div class="info-tit rel">
          <h2 class="tit dib">我的预约</h2>
        </div>
        <div class="order">
          <table class="table table-col-3">
            <thead>
              <tr>
                <th class="table-row-bd col-1 col-first">
                  <div class="right-bd">商品信息</div>
                </th>
                <th class="table-row-bd col-2">
                  <div class="right-bd">预约状态</div>
                </th>
                <th class="table-row-bd col-3 col-last">
                  <div>云码发放状态</div>
                </th>
              </tr>
            </thead>
            <tbody>
              <tr class="blank-row"></tr>
              <tr class="table-hd">
                <td colspan="3">预约时间：2014-4-22 12:33:33</td>
              </tr>
              <tr class="table-data">
                <td class="col-1 col-first">
                  <img class="order-item-pic dib fl" src="<?php echo $this->di['sysconfig']['staticServer'];?>images/mall/shoes-example.jpg" alt="云朵智能童鞋">
                  <div class="order-item-desc dib">
                    <p class="order-item-name">云朵智能童鞋</p>
                    <p class="order-item-info">颜色:黄色 尺码:32码</p>
                  </div>
                </td>
                <td class="col-2 tac">
                  <span class="color">预约成功</span>
                </td>
                <td class="col-3 tac col-last">
                  <div class="yunma-status">
                    <p class="color">恭喜获得云码：
                      <strong>XIDLS2IEKSDSIR87</strong>
                    </p>
                    <a href="#" class="btn btn-blue more-info">使用云码购买</a>
                  </div>
                  <div class="yunma-status dn">
                    <p class="c-grey">
                      <strong>XIDLS2IEKSDSIR87</strong>
                    </p>
                    <a href="#" class="btn btn-blue more-info disabled">已使用</a>
                  </div>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
      <!-- 正文部分结束 -->
    </div>
    <!-- 主体部分结束 -->
  </div>