<link rel="stylesheet" href="<?=$this->di['sysconfig']['staticServer'];?>css/mall/previous.css">
<a href="https://yunduotx.tmall.com" target="_blank">
<div class="index-row-1">
  <div class="w auto">
    <h2 class="text-hide">云朵陪伴 安心出游</h2>
    <p class="text-hide">任意购买两双云朵鞋（含替换鞋）  即赠迪士尼正品书包一个</p>
  </div>
</div>
</a>
<!-- 首屏结束 -->
<!-- 主体部分开始 -->
<div class="w auto">

  <div class="index-row-star fix">
    <p class="tit"><img class="vam" src="<?=$this->di['sysconfig']['staticServer'];?>images/previous/index-tit-marvel.jpg" alt="漫威"> <span>明星单品</span></p>
    <div class="box-l">
      <a href="/goods/index/12" class="tdn" title="蜘蛛侠款" target="_blank">
        <div class="show-zzx">
          <div class="info-group">
            <p>云朵智能定位童鞋 </p>
            <h2>蜘蛛侠款</h2>
            <p class="price"><em>￥</em>359</p>
            <del>原价 ￥888</del>
          </div>
        </div>
      </a>
    </div>
    <div class="box-r">
      <a href="/goods/index/26" class="tdn" title="钢铁侠款" target="_blank">
        <div class="show-gtx">
          <div class="info-group">
            <p>云朵智能定位童鞋 </p>
            <h2>钢铁侠款</h2>
            <p class="price"><em>￥</em>359</p>
            <del>原价 ￥888</del>
          </div>
        </div>
      </a>
      <a href="/goods/index/25" class="tdn" title="绿巨人款" target="_blank">
        <div class="show-ljr">
          <div class="info-group">
            <p>云朵智能定位童鞋 </p>
            <h2>绿巨人款</h2>
            <p class="price"><em>￥</em>359</p>
            <del>原价 ￥888</del>
          </div>
        </div>
      </a>
    </div>
  </div>

  <div class="index-row-recommend fix">
    <p class="tit">推荐商品</p>
    <div class="box-normal">
      <a href="/goods/index/23" title="美国队长盾牌款" target="_blank">
        <div class="recommend-box bd-t bd-l bd-r bd-b">
          <p>美国队长盾牌款</p>
          <h2 class="tit"><em>￥</em>359</h2>
          <del>原价￥888</del>
          <img src="<?=$this->di['sysconfig']['staticServer'];?>images/previous/index-s-mgdz1.jpg" alt="美国队长盾牌款">
        </div>
      </a>
      <a href="/goods/index/24" title="美国队长星条旗款" target="_blank">
      <div class="recommend-box bd-t bd-r bd-b">
        <p>美国队长星条旗款</p>
        <h2 class="tit"><em>￥</em>359</h2>
        <del>原价￥888</del>
        <img src="<?=$this->di['sysconfig']['staticServer'];?>images/previous/index-s-mgdz2.jpg" alt="美国队长星条旗款">
      </div>
      </a>
      <a href="/goods/index/14" title="蜘蛛侠高帮款" target="_blank">
      <div class="recommend-box bd-t bd-r bd-b">
        <p>蜘蛛侠高帮款</p>
        <h2 class="tit"><em>￥</em>359</h2>
        <del>原价￥888</del>
        <img src="<?=$this->di['sysconfig']['staticServer'];?>images/previous/index-s-zzx.jpg" alt="蜘蛛侠高帮款">
      </div>
      </a>
      <a href="/goods/index/28" title="冰雪奇缘安娜款" target="_blank">
      <div class="recommend-box bd-l bd-r bd-b">
        <p>冰雪奇缘安娜款</p>
        <h2 class="tit"><em>￥</em>359</h2>
        <del>原价￥888</del>
        <img src="<?=$this->di['sysconfig']['staticServer'];?>images/previous/index-s-an.jpg" alt="冰雪奇缘安娜款">
      </div>
      </a>
      <a href="/goods/index/27" title="冰雪奇缘艾莎款" target="_blank">
      <div class="recommend-box bd-r bd-b">
        <p>冰雪奇缘艾莎款</p>
        <h2 class="tit"><em>￥</em>359</h2>
        <del>原价￥888</del>
        <img src="<?=$this->di['sysconfig']['staticServer'];?>images/previous/index-s-bxqy.jpg" alt="冰雪奇缘艾莎款">
      </div>
      </a>
      <a href="/goods/index/29" title="银河护卫队款" target="_blank">
      <div class="recommend-box bd-r bd-b">
        <p>银河护卫队款</p>
        <h2 class="tit"><em>￥</em>359</h2>
        <del>原价￥888</del>
        <img src="<?=$this->di['sysconfig']['staticServer'];?>images/previous/index-s-hwd.jpg" alt="银河护卫队款">
      </div>
      </a>
    </div>
      <div class="box-older">
        <a href="/goods/index/31" title="云朵替换鞋" target="_blank">
          <div class="inner">
            <img class="change-tips" src="<?=$this->di['sysconfig']['staticServer'];?>images/previous/index-s-change-tips.jpg" alt="云朵替换鞋">
            <h2>云朵替换鞋</h2>
            <p class="desc">任意款式 随心替换</p>
            <p class="price"><em>￥</em>99</p>
            <img src="<?=$this->di['sysconfig']['staticServer'];?>images/previous/index-s-c-1.jpg" alt="云朵替换鞋">
          </div>
        </a>
        <a href="/goods/index/30" title="云朵替换鞋" target="_blank">
          <div class="inner">
            <img class="change-tips" src="<?=$this->di['sysconfig']['staticServer'];?>images/previous/index-s-change-tips.jpg" alt="云朵替换鞋">
            <h2>云朵替换鞋</h2>
            <p class="desc">任意款式 随心替换</p>
            <p class="price"><em>￥</em>159</p>
            <img src="<?=$this->di['sysconfig']['staticServer'];?>images/previous/index-s-c-2.jpg" alt="云朵替换鞋">
          </div>
        </a>
      </div>
  </div>

  <div class="parts-area fix">
    <p class="tit">配件专区</p>
    <a href="http://item.jd.com/1530589140.html" title="迪士尼书包" target="_blank">
    <div class="col-1">
      <div class="tit-group">
        <h3 class="sub-tit">迪士尼书包</h3>
        <p class="price"><em>￥</em>299</p>
<!--           <del>原价 ￥188</del> -->
      </div>
      <img src="<?=$this->di['sysconfig']['staticServer'];?>images/previous/index-s-bag.jpg" alt="迪士尼书包" class="disney-bags">
    </div>
    </a>
    <a href="http://item.jd.com/1422064401.html" title="云朵充电线" target="_blank">
    <div class="col-2">
      <div class="tit-group">
        <h3 class="sub-tit">云朵充电线</h3>
        <p class="price"><em>￥</em>39</p>
        <del>原价 ￥99</del>
      </div>
      <p class="tar">
        <img class="line" src="<?=$this->di['sysconfig']['staticServer'];?>images/previous/index-s-line.jpg" alt="云朵充电线">
      </p>
    </div>
    </a>
    <a href="http://item.jd.com/1530600382.html" title="云朵充电宝" target="_blank">
    <div class="col-3">
      <div class="tit-group">
        <h3 class="sub-tit">云朵充电宝</h3>
        <p class="price"><em>￥</em>88</p>
        <del>原价 ￥288</del>
      </div>
      <p class="tac">
        <img class="battery" src="<?=$this->di['sysconfig']['staticServer'];?>images/previous/index-s-battery.jpg" alt="云朵充电宝">
      </p>
    </div>
    </a>
  </div>
</div>
  <!--[include "../../include/service-desc.html"]-->
  <!-- 我是分割线 -->
<div class="section service-list">
    <div class="w auto tac">
        <img src="<?=$this->di['sysconfig']['staticServer'];?>images/previous/detail-12.jpg" alt="3M反光材质" class="dib">
    </div>
 </div>

