<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <meta name="keywords" content="云朵儿童安全鞋，云朵儿童，云朵安全，yunduokids,yunduo儿童安全鞋，云朵官方网站，云朵智能穿戴设备，儿童打拐，儿童安全">
    <meta name="description" content="云朵儿童安全鞋，是一款针对儿童与家长设计的软硬件结合的产品，通过童鞋内置设备与智能手机APP连接，实现与儿童安全鞋轻松关联，准确定位儿童安全鞋穿着者的所在位置。帮助家长及时了解小孩的出行情况。通过云朵APP任务设置，鼓励用户更注重家庭情感及宝宝养成。">
    <title>注册--云朵儿童安全官网</title>
    <link rel="shortcut icon" href="/favicon.ico">
    <!--[if lt IE 9]>
    <script src="/js/hooks/html5.js"></script>
    <![endif]-->
<link href="/css/bootstrap.min.css" rel="stylesheet" />
<link href="/css/bootstrap-responsive.min.css" rel="stylesheet" />
<link rel="stylesheet" href="/css/ace.min.css" />
<link rel="stylesheet" href="/css/ace-responsive.min.css" />
<link rel="stylesheet" href="/css/font-awesome.min.css" />
<link rel="stylesheet" href="/css/yunduo.css" />
<link rel="stylesheet" href="/css/ace-skins.min.css" />
<link rel="stylesheet" href="/css/ace-rtl.min.css" />
<link rel="stylesheet" type="text/css" href="/plugin/calendar/jscal2.css">
<link rel="stylesheet" type="text/css" href="/plugin/calendar/border-radius.css">
<link rel="stylesheet" type="text/css" href="/plugin/calendar/win2k.css">
<link href="/plugin/umeditor/themes/default/css/umeditor.css" type="text/css" rel="stylesheet">

<script src="/js/spm_modules/jquery/1.11.1/jquery-1.11.1.min.js"></script>
<script src="/js/spm_modules/bootstrap/bootstrap.min.js"></script>
<script src="/js/spm_modules/seajs/2.3.0/dist/sea.js"></script>
<script type="text/javascript" charset="utf-8" src="/plugin/umeditor/umeditor.config.js"></script>
<script type="text/javascript" charset="utf-8" src="/plugin/umeditor/umeditor.min.js"></script>
<script type="text/javascript" src="/plugin/umeditor/lang/zh-cn/zh-cn.js"></script>
<script type="text/javascript" src="/js/spm_modules/jquery-plugin/jquery.form.js"></script>
<script type="text/javascript" src="/plugin/calendar/calendar.js"></script>
<script type="text/javascript" src="/plugin/calendar/lang/en.js"></script>
<script src="/js/utils/common.js"></script>
</head>

<body style="background: #f3f3f3;">

<?php echo $this->getContent(); ?>

<iframe id="iframeA" name="iframeA" src="" width="0" height="0" style="display:none;"></iframe>
<script>

    window.admPath = '<?php echo $this->di['sysconfig']['admPath'];?>';

    window.onload=resizeWindow;

</script>

</body>

</html>
