<style type="text/css">
    .cate_id{
        display: none;
    }
</style>
<div class="page-header">
    <h1>
        <a href="/category">商品分类管理</a>
        <span class="pull-right">
            <a href="/category/operatecate">
                <button class="btn btn-small"><i class="icon-plus fa fa-plus"></i>添加分类</button>
            </a>
        </span>
    </h1>
</div>
<div id = "yunduo-error-msg">

</div>
<div class="row-fluid">
    <div class="span12">
        <table class="table table-striped table-bordered table-hover" style="margin-bottom=10px;" id="sample-table-1">
            <thead>
                <tr>
                    <th class="center">   名称    </th>
                    <th class="center">   描述    </th>
                    <th  class="center">  关键字    </th>
                    <th  class="center">  排序    </th>
                    <th  class="center">  是否显示    </th>
                    <th  class="center">  操作   </th>
                </tr>
            </thead>
            <tbody>
                <?php
                    function _getCate($key, $list, $num = 0, $flag = '&nbsp;&nbsp;&nbsp;&nbsp;')
                    {
                        for ($i=0; $i < $num ; $i++)
                        {
                            $flag .= '&nbsp;&nbsp;&nbsp;&nbsp;';
                        }
                        $flags = $flag . '└─';
                        foreach ($list[$key]['child'] as $key2 => $val)
                        {
                            $val['gcat_show']=$val['gcat_show']==1?'<span class="badge badge-success label-large">显示</span>':'<span class="badge badge-grey label-large">不显示</span>';
                            echo "<tr>
                                            <td class=\"cate_id\">$val[gcat_id]</td>
                                            <td>$flags$val[gcat_name]</td>
                                            <td>$val[gcat_desc]</td>
                                            <td>$val[gcat_keywords]</td>
                                            <td>$val[gcat_order]</td>
                                            <td>$val[gcat_show]</td>
                                            <td>
                                                <a href=\"/category/operatecate?cid=$val[gcat_id]\"  class=\"btn btn-mini\"><i class=\"icon-pencil\"></i></a>
                                                <a href=\"javascript:void(0);\"  class=\"btn btn-mini cate_del\"><i class=\"icon-trash\"></i></a>
                                            </td>
                                        </tr>";
                            if(isset($list[$key2]) && !empty($list[$key2]))
                            {
                                $num++;
                                _getCate($key2, $list, $num);
                            }
                        }
                    }
                    foreach ($list as $key => $val)
                        {
                            if(isset($val['gcat_parent_id'] ) && $val['gcat_parent_id'] == 0)
                            {
                                $val['gcat_show']=$val['gcat_show']==1?'<span class="badge badge-success label-large">显示</span>':'<span class="badge badge-grey label-large">不显示</span>';
                                echo "<tr>
                                                <td class=\"cate_id\">$val[gcat_id]</td>
                                                <td>$val[gcat_name]</td>
                                                <td>$val[gcat_desc]</td>
                                                <td>$val[gcat_keywords]</td>
                                                <td>$val[gcat_order]</td>
                                                <td>$val[gcat_show]</td>
                                                <td>
                                                    <a href=\"/category/operatecate?cid=$val[gcat_id]\" class=\"btn btn-mini\"><i class=\"icon-pencil\"></i></a>
                                                    <a href=\"javascript:void(0);\"  class=\"btn btn-mini cate_del\"><i class=\"icon-trash\"></i></a>
                                                </td>
                                            </tr>";
                                if(!empty($val['child']))
                                {
                                    foreach ($val['child'] as $key => $value)
                                    {
                                        $value['gcat_show']=$value['gcat_show']==1?'<span class="badge badge-success label-large">显示</span>':'<span class="badge badge-grey label-large">不显示</span>';
                                        echo "<tr>
                                                        <td class=\"cate_id\">$value[gcat_id]</td>
                                                        <td>└─$value[gcat_name]</td>
                                                        <td>$value[gcat_desc]</td>
                                                        <td>$value[gcat_keywords]</td>
                                                        <td>$value[gcat_order]</td>
                                                        <td>$value[gcat_show]</td>
                                                        <td>
                                                            <a href=\"/category/operatecate?cid=$value[gcat_id]\" class=\"btn btn-mini cate_edit\"><i class=\"icon-pencil\"></i></a>
                                                            <a href=\"javascript:void(0);\"  class=\"btn btn-mini cate_del\"><i class=\"icon-trash\"></i></a>
                                                        </td>
                                                    </tr>";
                                        if(isset($list[$key]) && !empty($list[$key]))
                                        {
                                            _getCate($key, $list);
                                        }
                                    }
                                }
                            }
                        }
                ?>
            </tbody>
        </table>
    </div>
</div>
<script >
    seajs.use("<?php echo $this->di['sysconfig']['staticServer'];?>js/modules/category/main");
</script>
