<div class="page-header">
    <h1>
        <a href="/category">商品分类管理</a>
        <small>
            <i class="icon-double-angle-right fa fa-angle-double-right"></i>
            <?php if($this->request->get('cid')):?>
                编辑分类
            <?php else:?>
                添加分类
            <?php endif;?>
        </small>
    </h1>
</div>
<div class="row-fluid">
     <div class="span12">
         <div class="widget-box">
             <div class="widget-header widget-header-blue widget-header-flat">
                 <h4 class="lighter">
                 分类管理</h4>
            </div>
            <div id = "yunduo-error-msg">

            </div>
        <div class="widget-body">
          <div class="widget-main">
            <div class="row-fluid">
              <form id = "cate-form" class="form-horizontal">
                  <?php if(isset($cateInfo['gcat_id'])) :?>
                      <input type="hidden" value="<?=$cateInfo['gcat_id']?>" name="cid" id="cid" class="required"/>
                  <?php endif;?>
                     <div class="control-group">
                            <label class="control-label"><small class="text-error"> * </small> 分类名称 </label>
                            <div class="controls">
                              <input type="text" value="<?=isset($cateInfo['gcat_name'])?$cateInfo['gcat_name']:''?>" name="name" class="required"/>
                              <span class="help-inline"></span>
                            </div>
                      </div>

                      <div class="control-group">
                           <label class="control-label"><small class="text-error" > * </small> 所属分类 </label>
                              <div class="controls">
                                  <?php echo $cateList;?>
                                  <span class="help-inline"></span>
                              </div>
                      </div>

                      <div class="control-group">
                            <label class="control-label">排序 </label>
                            <div class="controls">
                              <input type="text" class="require" value="<?=isset($cateInfo['gcat_order'])?$cateInfo['gcat_order']:0?>" name="order"/>
                              <span class="help-inline">数值越大排越前面</span>
                            </div>
                      </div>

                      <div class="control-group">
                            <label class="control-label"><small class="text-error"> * </small> 是否显示 </label>
                            <div class="controls">
                                  <input type="radio" value="1" <?=isset($cateInfo['gcat_show']) && $cateInfo['gcat_show'] == 1?'checked':''?> name="show" /><span class="lbl">显示</span>
                                    <input type="radio" value="3" <?=isset($cateInfo['gcat_show']) && $cateInfo['gcat_show'] == 3?'checked':''?> name="show" /><span class="lbl">不显示</span>
                                     <span class="help-inline"></span>
                            </div>
                      </div>

                      <div class="control-group">
                            <label class="control-label">关键字 </label>
                            <div class="controls">
                              <input type="text" value="<?=isset($cateInfo['gcat_keywords'])?$cateInfo['gcat_keywords']:''?>" name="keyword"/>
                              <span class="help-inline"></span>
                            </div>
                      </div>

                      <div class="control-group">
                            <label class="control-label"> 分类描述 </label>
                            <div class="controls">
                              <textarea name="desc" rows="6" style="width:360px"><?=isset($cateInfo['gcat_desc'])?$cateInfo['gcat_desc']:''?></textarea>
                              <span class="help-inline"></span>
                            </div>
                      </div>

                      <button type="button" id="cate-submit" class="btn">确认提交</button>
                    </form>
                  </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script >
    var pid = <?=isset($cateInfo['gcat_parent_id'])?$cateInfo['gcat_parent_id']:0?>;
    if(pid)
        $("select[name='gcat_id']").val(pid);
    seajs.use("<?php echo $this->di['sysconfig']['staticServer'];?>js/spm_modules/jquery-plugin/jquery.validate.js");
    seajs.use("<?php echo $this->di['sysconfig']['staticServer'];?>js/modules/category/operatecate");
</script>