<link rel="stylesheet" href="/css/jquery.bigautocomplete.css" type="text/css" />
<script type="text/javascript" src="/js/spm_modules/jquery-plugin/jquery.bigautocomplete.js"></script>
<div class="page-header">
  <h1>
       <a href="/coupons/listCouponsRule">优惠券规则管理</a>
      <small>
          <i class="icon-double-angle-right"></i>
       添加优惠券规则
      </small>
  </h1>
</div>
<div class="row-fluid">
    <div class="span12" >
        <div class="widget-box">
            <div class="widget-header widget-header-blue widget-header-flat">
                <h4 class="lighter">
                 添加优惠券规则</h4>
            </div>
        <div id = "yunduo-error-msg">

        </div>
        <?php  if(!empty($error)) echo "<script>yunduoErrorShow(" .json_encode(json_decode($error)->msg). ");</script>"; ?>
            <div class="widget-body">
                <div class="widget-main">
          <div class="row-fluid">
            <form id="itemForm"  class="form-horizontal form addCouponsRule-form"  action="/coupons/addCouponsRule" method="POST" enctype="multipart/form-data">

            <div class="control-group">
                  <label class="control-label"><small class="text-error"> * </small> 规则名称</label>
                  <div class="controls">
                  <select name="rangeType" class= 'rangeType'>
                      <option class="change_op" value="1" <?php if($this->request->get('rangeType') == '1') echo 'selected="selected"'?>>全部商品</option>
                      <option class="change_op" value="3" <?php if($this->request->get('rangeType') == '3') echo 'selected="selected"'?>>指定商品</option>
                      <option class="change_op" value="5" <?php if($this->request->get('rangeType') == '5') echo 'selected="selected"'?>>指定分类</option>
                  </select>
                    <span class="help-inline"></span>
                  </div>
            </div>
            <div class="control-group catname range" style="display:none;">
                  <label class="control-label"><small class="text-error"> * </small> 分类名称</label>
                  <div class="controls">
                    <input type="text" id="catname"/>
                    <input type="hidden" name="range-cid" id="catid" value="<?php echo $this->request->get('rang');?>" />
                    <span class="help-inline"></span>
                  </div>
            </div>
            <div class="control-group goodname rang" style="display:none;">
                  <label class="control-label"><small class="text-error"> * </small> 商品名称</label>
                  <div class="controls">
                    <input type="text" id="goodname"/>
                    <input type="hidden" name="range-gid" id="gid"  value="<?php echo $this->request->get('rang');?>"/>
                    <span class="help-inline"></span>
                  </div>
            </div>
            <div class="control-group">
                  <label class="control-label"><small class="text-error"> * </small> 名称</label>
                  <div class="controls">
                    <input type="text" name="name" class=""   value="<?php echo $this->request->get('name');?>" />
                    <span class="help-inline"></span>
                  </div>
            </div>
            <div class="control-group">
                  <label class="control-label"><small class="text-error"> * </small> 最小金额</label>
                  <div class="controls">
                    <input type="text" name="minAmount" class=""    value="<?php echo $this->request->get('minAmount');?>"/>
                    <span class="help-inline">需要满足的最小金额，0为不限</span>
                  </div>
            </div>
            <div class="control-group">
                  <label class="control-label"><small class="text-error"> * </small> 最大金额</label>
                  <div class="controls">
                    <input type="text" name="maxAmount" class=""   value="<?php echo $this->request->get('maxAmount');?>" />
                    <span class="help-inline">参加活动的上线金额，0为不限</span>
                  </div>
            </div>
             <div class="control-group">
                  <label class="control-label"><small class="text-error"> * </small> 抵消金额</label>
                  <div class="controls">
                    <input type="text" name="amount" class=""   value="<?php echo $this->request->get('amount');?>" />
                    <span class="help-inline">达到条件后减免的金额 </span>
                  </div>
            </div>
            <div class="control-group">
                 <label class="control-label"><small class="text-error" class="required" > * </small> 状态 </label>
                    <div class="controls">
                 <select name="status">
                    <option class="change_op" value="1" <?php if($this->request->get('status') == '1') echo 'selected="selected"'?>>可用</option>
                    <option class="change_op" value="3" <?php if($this->request->get('status') == '3') echo 'selected="selected"'?>>禁用</option>
                </select>
                 </div>
            </div>
                <button type="submit" id="form_submit" class="btn">确认提交</button>
                </form>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
<script >
    seajs.use("<?php echo $this->di['sysconfig']['staticServer'];?>js/modules/coupons/main");
    seajs.use("<?php echo $this->di['sysconfig']['staticServer'];?>js/spm_modules/jquery-plugin/jquery.validate.js");
    seajs.use("<?php echo $this->di['sysconfig']['staticServer'];?>js/modules/coupons/couponsValidate");
</script>