<div class="page-header">
    <h1>
        <a href="/coupons/listCouponsRule">优惠券规则管理</a>
        <span class="pull-right">
            <a href="/coupons/addCouponsRule">
                <button class="btn btn-small"><i class="icon-plus"></i>添加优惠券</button>
            </a>
        </span>
    </h1>
</div>
<div class="row-fluid alert alert-block" style="margin-bottom: 20px;padding-top:-100px'">
    <div class="span10">
        <div class="form-search pull-left">
        <form action="" method="get" accept-charset="utf-8" >
           <span>规则名称：</span>
           <span class="input-icon">
                <input type="text"  autocomplete="off" name="name" id="form-search-input" class="input-big nav-form-search-input" placeholder="搜索..." value="">
                <i style="padding-left:8px;" class="icon-search nav-search-icon"></i>
                <i id="form-search-clear" class="icon-remove nav-remove-icon" style="left:auto;right:3px;cursor:pointer;"></i>
            </span>

                      状态：
         <select id="form-search-field-select" style="width: 110px;" name="status">
         <option value="1">可用</option>
         <option value="3">禁用</option>
         <option value="0">全部</option>
           </select>
            <input type="submit" name="" value="搜索" class="btn btn-small" >
        </div>
</form>

    </div>
</div>
<div class="row-fluid">
    <div class="span12">
        <table class="table table-striped table-bordered table-hover" style="margin-bottom=10px;" id="sample-table-1">
            <thead>
                <tr>
                    <th class="center">
                        <label>
                            <input type="checkbox" id="chk-all">
                            <span class="lbl"></span>
                        </label>
                    </th>
                    <th class="center"> 规则id </th>
                    <th> 规则名称 </th>
                    <th> 规则适用类型 </th>
                    <th > 规则适用范围 </th>
                    <th> 规则详情 </th>
                    <th > 规则状态 </th>
                    <th> 添加时间 </th>
<!--                     <th> 操作 </th> -->
                </tr>
            </thead>
            <tbody>
            <?php foreach($couponsRuleslist as $v):?>
             <tr>
             <tr>
                    <td class="center"><label><input type="checkbox"  class="chk-item"  value="<?php echo $v['cr_id'];?>"/> <span class="lbl"></span></label></td>
                    <td class="center"><input type="hidden" class="crid" value="<?php echo $v['cr_id'];?>"><?php echo $v['cr_id'];?></td>
                    <td><?php echo $v['cr_name'];?></td>
                    <td><?php if($v['cr_range_type'] == 3) echo '指定商品';else if($v['cr_range_type'] == 5) echo '指定商品分类';else echo '所有商品';?></td>
                    <td><?php echo $v['cr_range']?></td>
                    <td><?php $info = json_decode($v['cr_info']); echo '最小金额：'.$info->minAmount.' 最大金额：'.$info->maxAmount.' 抵消金额：'.$info->amount;?></td>
                    <td id="cr_status"><input type="hidden" class="cr_status" value="<?php echo $v['cr_status'];?>"><?php echo $v['cr_status'] == '1'?'可用':'禁用';?>
                    </td>
                    <td><?php echo date('Y-m-d H:i:s',$v['cr_addtime'])?></td>
<!--                     <td> <a href="javascript:void(0)" class="btn btn-mini couponsRules_edit" data="<?php echo $v['cr_id'];?>">属性编辑</a></td> -->
                </tr>
            <?php endforeach;?> 
            </tbody>
        </table>
            <p>
        <span>
            状态：
         <select id="set-select" style="width: 110px;" name="status" >
         <option value="1" <?php if($this->request->get('status') == '1') echo 'selected="selected"';?>>可用</option>
         <option value="3" <?php if($this->request->get('status') == '3') echo 'selected="selected"';?>>禁用</option>
           </select></span>
        <span><a href="javascript:void(0);"  class="btn btn-mini" id="listCouponsRule">提交</a></span></p>
        <?php echo $page;?>
    </div>
</div>
</div>
</div>
<script >
    seajs.config({
        base : "<?php echo $this->di['sysconfig']['staticServer'];?>js/",
        alias : {
            'chkAll' : 'utils/chkAll'
        }
    });
    seajs.use("<?php echo $this->di['sysconfig']['staticServer'];?>js/modules/coupons/index");
    seajs.use("<?php echo $this->di['sysconfig']['staticServer'];?>js/modules/coupons/main");
</script>

