<div class="page-header">
    <h1>
        <a href="/coupons/listCoupons">优惠券管理</a>
        <span class="pull-right">
            <a href="/coupons/addCoupons">
                <button class="btn btn-small"><i class="icon-plus"></i>添加优惠券</button>
            </a>
        </span>
    </h1>
</div>
<div class="row-fluid alert alert-block" style="margin-bottom: 20px;padding-top:-100px'" >
    <div class="span10">
        <div class="form-search pull-left">
        <form action="" method="get" accept-charset="utf-8">
           <span>优惠券号码：</span>
           <span class="input-icon">
                <input type="text"  autocomplete="off" name="sn" id="form-search-input" class="input-big nav-form-search-input" placeholder="搜索..." value="">
                <i style="padding-left:8px;" class="icon-search nav-search-icon"></i>
                <i id="form-search-clear" class="icon-remove nav-remove-icon" style="left:auto;right:3px;cursor:pointer;"></i>
            </span>
           开始时间： <input type="text"  name="starTime"   id ="start_uploadtime" class="required"  />
           结束时间：<input type="text"  name="endTime"  id="end_uploadtime" class="required"  />
                      状态：
         <select id="form-search-field-select" style="width: 110px;" name="status">
         <option value="1">可用</option>
         <option value="3">禁用</option>
         <option value="0">全部</option>
           </select>
            <input type="submit" name="" value="搜索" class="btn btn-small" >
        </div>
</form>

    </div>
</div>
<div class="row-fluid">
    <div class="span12">
        <table class="table table-striped table-bordered table-hover" style="margin-bottom=10px;" id="sample-table-1">
            <thead>
                <tr>
                    <th class="center">
                        <label>
                            <input type="checkbox" id="chk-all">
                            <span class="lbl"></span>
                        </label>
                    </th>
                    <th class="center"> 优惠券id </th>
                    <th> 规则id </th>
                    <th> 优惠券号码 </th>
                    <th > 有效期开始时间 </th>
                    <th > 有效期结束时间 </th>
                    <th> 使用者ID </th>
                    <th> 使用时间 </th>
                    <th> 状态 </th>
                    <th> 生成时间 </th>
<!--                     <th> 操作 </th> -->
                </tr>
            </thead>
            <tbody>
            <?php foreach($couponslist as $v):?>
             <tr>
             <tr>
                    <td class="center"><label><input type="checkbox"  class="chk-item"  value="<?php echo $v['cp_id'];?>"/> <span class="lbl"></span></label></td>
                    <td class="center"><?php echo $v['cp_id'];?></td>
                    <td><input type="hidden" class="cpid" value="<?php echo $v['cp_id'];?>"><?php echo $v['cr_id'];?></td>
                    <td><?php echo $v['cp_sn']?></td>
                    <td><?php echo date('Y-m-d H:i:s',$v['cp_start_time'])?></td>
                    <td><?php echo date('Y-m-d H:i:s',$v['cp_end_time'])?></td>
                    <td> <?php echo $v['u_id']?> </td>
                    <td><?php echo $v['cp_used_time'] == true ?date('Y-m-d H:i:s',$v['cp_used_time']):$v['cp_used_time']?></td>
                    <td id="cp_status"><input type="hidden" class="cp_status" value="<?php echo $v['cp_status'];?>"> <?php echo $v['cp_status'] == '1'?'可用':'禁用';?>
                    </td>
                    <td><?php echo date('Y-m-d H:i:s',$v['cp_addtime'])?></td>
<!--                     <td> <a href="javascript:void(0)" class="btn btn-mini coupons_edit" data="<?php echo $v['cp_id'];?>">属性编辑</a></td> -->
                </tr>
            <?php endforeach;?> 
            </tbody>
        </table>
        <p>
        <span>
            状态：
         <select id="set-select" style="width: 110px;" name="status" >
         <option value="1" <?php if($this->request->get('status') == '1') echo 'selected="selected"';?>>可用</option>
         <option value="3" <?php if($this->request->get('status') == '3') echo 'selected="selected"';?>>禁用</option>
           </select></span>
        <span><a href="javascript:void(0);"  class="btn btn-mini" id="listCoupons">提交</a></span></p>
        <?php echo $page;?>
    </div>
</div>
</div>
</div>
<script >
    seajs.config({
        base : "<?php echo $this->di['sysconfig']['staticServer'];?>js/",
        alias : {
            'chkAll' : 'utils/chkAll'
        }
    });
    seajs.use("<?php echo $this->di['sysconfig']['staticServer'];?>js/modules/coupons/index");
    seajs.use("<?php echo $this->di['sysconfig']['staticServer'];?>js/modules/coupons/main");
</script>

