<style type="text/css">
.sku_ul {
    list-style: none;
}
.sku_ul li {
    margin-right: 10px;
    //border: 1px solid #999;
    color: #4D4D4D;
    padding: 2px 8px;
    line-height: 16px;
    font-size: 12px;
    float: left;
    cursor: pointer;
}
table.gridtable {
    font-family: verdana,arial,sans-serif;
    font-size:11px;
    color:#333333;
    border-width: 1px;
    border-color: #666666;
    border-collapse: collapse;
}
table.gridtable th {
    border-width: 1px;
    padding: 8px;
    border-style: solid;
    border-color: #666666;
    background-color: #dedede;
}
table.gridtable td {
    border-width: 1px;
    padding: 8px;
    border-style: solid;
    border-color: #666666;
    background-color: #ffffff;
}
table th{
    width :100px;
    text-align: center;
}
em{
  font-style: normal;
}
</style>
<div class="page-header">
    <h1>
        <a href="/item">商品管理</a>
        <small>
            <i class="icon-double-angle-right fa fa-angle-double-right"></i>
            添加商品
        </small>
    </h1>
</div>
<div class="row-fluid">
    <div class="span12">
      <div class="widget-box">
          <div class="widget-header widget-header-blue widget-header-flat">
                <h4 class="lighter">
                 添加商品</h4>
          </div>
          <div id = "yunduo-error-msg">

        </div>
      <div class="widget-body">
        <div class="widget-main">
          <div class="row-fluid">
            <form id = "item-form" class="form-horizontal" action="insertitem" method="POST" enctype="multipart/form-data">

            <div class="control-group">
                 <label class="control-label"><small class="text-error" > * </small> 所属分类 </label>
                    <div class="controls">
                        <?php echo $cateList;?>
                        <span class="help-inline"></span>
                    </div>
            </div>

            <div class="control-group">
                  <label class="control-label"><small class="text-error"> * </small> 商品名称 </label>
                  <div class="controls">
                    <input type="text" name="goods_name" class="required" id="goods-name"/>
                    <span class="help-inline"></span>
                  </div>
            </div>

            <div class="control-group">
                  <label class="control-label"> 商品简介 </label>
                  <div class="controls">
                    <textarea  name="goods_brief"></textarea>
                    <span class="help-inline"></span>
                  </div>
            </div>

            <div class="control-group">
                  <label class="control-label"><small class="text-error"> * </small> 商品货号 </label>
                  <div class="controls">
                    <input type="text"  name="goods_sn" class="required" id="goods-sn"/>
                    <span class="help-inline">货号必须唯一</span>
                  </div>
            </div>

            <div class="control-group">
                  <label class="control-label"> 字体样式选择 </label>
                  <div class="controls">
                        <input type="radio" checked="checked" value="" name="goods_name_style" /><span class="lbl">默认</span>
                        <input type="radio"  value="font:13px;color:red" name="goods_name_style" /><span class="lbl" style="color:red;font-size:13px">看</span>
                        <input type="radio"  value="font:14px;color:blue" name="goods_name_style" /><span class="lbl" style="font:14px;color:blue">再看看</span>
                        <input type="radio"  value="font:14px;color:green;font-weight:bold" name="goods_name_style" /><span class="lbl" style="font:14px;color:green;font-weight:bold">喜欢吗</span>
                    <span class="help-inline"></span>
                  </div>
            </div>

            <div class="control-group">
                  <label class="control-label"> 点击数 </label>
                  <div class="controls">
                    <input type="text" class="required number" name="goods_clicks"/>
                    <span class="help-inline"></span>
                  </div>
            </div>

            <div class="control-group">
                  <label class="control-label"> 卖出数 </label>
                  <div class="controls">
                    <input type="text" class="required number" name="goods_sales"/>
                    <span class="help-inline"></span>
                  </div>
            </div>

            <div class="control-group">
                  <label class="control-label"><small class="text-error"> * </small> 市场价 </label>
                  <div class="controls">
                    <input type="text" class="required number" name="goods_market"/>
                    <span class="help-inline">精确到0.01元</span>
                  </div>
            </div>

            <div class="control-group">
                  <label class="control-label"><small class="text-error"> * </small> 本店价 </label>
                  <div class="controls">
                    <input type="text" class="required number" name="goods_price"/>
                    <span class="help-inline">精确到0.01元</span>
                  </div>
            </div>

            <div class="control-group">
                  <label class="control-label"> 促销价 </label>
                  <div class="controls">
                    <input type="text" class="number" name="goods_promote"/>
                    <span class="help-inline">精确到0.01元</span>
                  </div>
            </div>

            <div class="control-group">
                  <label class="control-label"> 促销开始时间 </label>
                  <div class="controls">
                    <input type="text"  name="goods_promote_start" id="start-promote-time" />
                    <span class="help-inline"></span>
                  </div>
            </div>

            <div class="control-group">
                  <label class="control-label">促销结束时间 </label>
                  <div class="controls">
                    <input type="text"  name="goods_promote_end" id="end-promote-time"/>
                    <span class="help-inline"></span>
                  </div>
            </div>

            <div class="control-group">
                  <label class="control-label"><small class="text-error"> * </small> 上架时间 </label>
                  <div class="controls">
                    <input type="text" class="required" name="goods_start" id="start-time"/>
                    <span class="help-inline"></span>
                  </div>
            </div>

            <div class="control-group">
                  <label class="control-label"><small class="text-error"> * </small> 下架时间 </label>
                  <div class="controls">
                    <input type="text" class="required" name="goods_end" id="end-time" />
                    <span class="help-inline"></span>
                  </div>
            </div>

            <div class="control-group">
                  <label class="control-label"> 标签 </label>
                  <div class="controls">
                    <input type="text"  name="goods_tags"/>
                    <span class="help-inline">填写商品标签，不超过５个，以半角,隔开</span>
                  </div>
            </div>

            <div class="control-group">
                  <label class="control-label"> 商品详细介绍 </label>
                  <div class="controls">
                        <script type="text/plain" id="good-desc" name = "goods_desc" style="width:1000px;height:240px;">商品详细介绍</script>
                    <span class="help-inline"></span>
                  </div>
            </div>

            <div class="control-group">
                  <label class="control-label"><small class="text-error"> * </small> 商品列表图 </label>
                  <div class="controls">
                    <input type="file"  name="goods_img"/>
                  </div>
            </div>

            <div class="control-group">
                  <label class="control-label"><small class="text-error"> * </small> 商品缩略图 </label>
                  <div class="controls">
                      <table width="100%" id="thumb-table" style="display: table;" align = "left">
                          <tbody>
                            <tr>
                              <td>
                                <a href="javascript:void(0);" class="add-img">[+]</a>
                                上传文件 <input type="file" name="goods_pics[]">
                              </td>
                            </tr>
                           <tr>
                          </tr>
                    </tbody>
                  </table>
                  <span class="help-inline">
                      用来显示详细商品里面的多组小图显示大图和放大图的数据
                  </span>
                  </div>
            </div>

                  <div class="control-group">
                        <label for="form-field-1" class="control-label">
                            <small class="text-error" > * </small>商品状态</label>
                        <div class="controls">
                          <input type="radio" checked="checked" value="1" name="goods_status" /><span class="lbl">销售</span>
                          <input type="radio" value="3" name="goods_status" /><span class="lbl">预售</span>
                           <span class="help-inline"></span>
                        </div>
                  </div>

            <div class="control-group">
                  <label class="control-label"><small class="text-error"> * </small> 商品类型 </label>
                  <div class="controls">
                        <input type="radio" checked="checked" value="1" name="goods_type" /><span class="lbl">非赠品或配件</span>
                          <input type="radio" value="3" name="goods_type" /><span class="lbl">赠品或配件</span>
                           <span class="help-inline"></span>
                  </div>
            </div>

            <div class="control-group">
                  <label class="control-label"><small class="text-error"> * </small> 排序 </label>
                  <div class="controls">
                    <input type="text"  name="goods_order"/>
                    <span class="help-inline">数值越大排越前面</span>
                  </div>
            </div>

            <div class="control-group">
                  <label class="control-label"><small class="text-error"> * </small> 是否新品 </label>
                  <div class="controls">
                        <input type="radio" checked="checked" value="1" name="goods_is_new" /><span class="lbl">非新品</span>
                          <input type="radio" value="3" name="goods_is_new" /><span class="lbl">新品</span>
                           <span class="help-inline"></span>
                  </div>
            </div>

            <div class="control-group">
                  <label class="control-label"><small class="text-error"> * </small> 是否促销 </label>
                  <div class="controls">
                        <input type="radio" checked="checked" value="1" name="goods_is_promote" /><span class="lbl">非促销</span>
                          <input type="radio" value="3" name="goods_is_promote" /><span class="lbl">促销</span>
                           <span class="help-inline"></span>
                  </div>
            </div>

            <div class="control-group">
                  <label class="control-label"><small class="text-error"> * </small> 是否热销 </label>
                  <div class="controls">
                        <input type="radio" checked="checked" value="1" name="goods_is_hot" /><span class="lbl">非热销</span>
                          <input type="radio" value="3" name="goods_is_hot" /><span class="lbl">热销</span>
                           <span class="help-inline"></span>
                  </div>
            </div>

            <div class="control-group">
                  <label class="control-label"><small class="text-error"> * </small> 是否保修 </label>
                  <div class="controls">
                        <input type="radio" checked="checked" value="1" name="goods_is_warranty" /><span class="lbl">是</span>
                          <input type="radio" value="3" name="goods_is_warranty" /><span class="lbl">否</span>
                           <span class="help-inline"></span>
                  </div>
            </div>

            <div class="control-group">
                  <label class="control-label"><small class="text-error"> * </small> 是否包邮 </label>
                  <div class="controls">
                        <input type="radio" checked="checked" value="1" name="goods_is_shipping" /><span class="lbl">是</span>
                          <input type="radio" value="3" name="goods_is_shipping" /><span class="lbl">否</span>
                           <span class="help-inline"></span>
                  </div>
            </div>

            <div class="control-group">
                  <label class="control-label"><small class="text-error"> * </small> 属性选择 </label>
                  <div class="controls">
                        <table cellspacing="5" cellpadding="0" border="0" style="text-align: center;">
                          <tbody>
                          <?php foreach ($attrList as $attrs): ?>
                            <tr>
                              <td height="30" data-id="<?=$attrs['attrs_id']?>" data-name="<?=$attrs['attrs_name']?>" ><input type="hidden" value="<?=$attrs['attrs_id']?>" name="goods-attrs[]" /><?=$attrs['attrs_name']?>:</td>
                              <td>
                              <?php if(!empty($attrs['child'])):?>
                                <ul class="sku_ul">
                                <?php foreach ($attrs['child'] as $attr) :?>
                                  <li data-id="<?=$attr['attrs_id']?>" data-name="<?=$attr['attrs_name']?>">
                                            <input name="form-field-checkbox" type="checkbox" class="attr-checked">
                                            <span class="lbl"><?=$attr['attrs_name']?></span>
                                  </li>
                              <?php endforeach;?>
                                </ul>
                            <?php endif;?>
                                </td>
                            </tr>
                          <?php endforeach ?>
                          </tbody>
                        </table>
                           <span class="help-inline"></span>
                  </div>
                  <div class="controls">
                        <a href="javascript:void(0)" class="btn btn-warning" id="attr-generate">生成商品属性组合列表</a>
                  </div>
            </div>

            <div class="control-group" id="goog-attr-table" style="display:none">
                  <label class="control-label">组合属性表 </label>
                  <div class="controls">

                  </div>
            </div>
            <button type="submit" class="btn">确认提交</button>
           </form>
         </div>
       </div>
     </div>
    </div>
  </div>
</div>

<script >
    seajs.use("<?php echo $this->di['sysconfig']['staticServer'];?>js/spm_modules/jquery-plugin/jquery.validate.js");
    seajs.use("<?php echo $this->di['sysconfig']['staticServer'];?>js/modules/item/main");
</script>
