<div class="page-header">
    <h1>
        <a href="/item">商品管理</a>
        <span class="pull-right">
            <a href="/item/additem">
                <button class="btn btn-small"><i class="icon-plus fa fa-plus"></i>添加商品</button>
            </a>
        </span>
    </h1>
</div>
<div id = "yunduo-error-msg">

</div>
<div class="row-fluid">
    <div class="span12 alert">
        <div class="form-search pull-left" style="margin-bottom:10px;">
                    商品状态：<select id="goods-status" style="width: 110px;">
                        <option value = "0">全部</option>
                        <option <?php if($this->request->get('goods_status') == 1) echo 'selected';?> value = "1">销售</option>
                        <option <?php if($this->request->get('goods_status') == 3) echo 'selected';?> value = "3">预售</option>
                   </select>
                   <span class="input-icon">
                   <input type="text" style="width: 120px;margin:0 0 0 5px;" autocomplete="off" id="goods-sn"　class="input-small nav-form-search-input" placeholder="商品货号" value="<?php echo  $this->request->get('goods_sn');?>">
                        <i style="padding-left:8px;" class="icon-search nav-search-icon"></i>
                        <!-- <i id="form-search-clear" class="icon-remove nav-remove-icon" style="left:auto;right:3px;cursor:pointer;"></i> -->
                    </span>
                         <span class="input-icon">
                        <input type="text" style="width: 120px;margin:0 0 0 5px;" autocomplete="off" id="goods-name"　class="input-small nav-form-search-input" placeholder="商品名称" value="<?php echo  $this->request->get('goods_name');?>">
                        <i style="padding-left:8px;" class="icon-search nav-search-icon"></i>
                    </span>
                    <button class="btn btn-small btn-success" type="button" id="search"><i class="icon-search"></i>搜索</button>
        </div>
    </div>
</div>
<div class="row-fluid">
    <div class="span12">
        <table class="table table-striped table-bordered table-hover" style="margin-bottom=10px;" id="sample-table-1">
            <thead>
                <tr>
                    <th class="center">
                        <label>
                            <input type="checkbox" id="chk-all">
                            <span class="lbl"></span>
                        </label>
                    </th>
                    <th>   商品货号    </th>
                    <th >  所属分类名    </th>
                    <th >  商品名称    </th>
                    <th >  商品状态    </th>
                    <th >  点击数    </th>
                    <th >  卖出数    </th>
                    <th >  库存数    </th>
                    <th >  可卖数    </th>
                    <th >  市场价    </th>
                    <th >  本店价    </th>
                    <th >  促销价    </th>
                    <th >  新品    </th>
                    <th >  促销    </th>
                    <th >  热销    </th>
                    <th >  保修    </th>
                    <th >  包邮    </th>
                    <th >  操作   </th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($list as $good):?>
                    <tr>
                        <input type="hidden" class="goos-id" value="<?=$good['goods_id']?>" />
                        <td class="center"><label><input type="checkbox"  class="chk-item"  value="<?=$good['goods_id']?>"/> <span class="lbl"></span></label></td>
                        <td><?=$good['goods_sn']?></td>
                        <td><?=$cate[$good['gcat_id']]?></td>
                        <td><a href = "<?=$this->di['sysconfig']['domain']?>/goods/index/<?=$good['goods_id']?>" target="_blank"><?=$good['goods_name']?></a></td>
                        <td><?=$good['goods_status'] == 1?'销售':'预售'?></td>
                        <td><?=$good['goods_clicks']?></td>
                        <td><?=$good['goods_sales']?></td>
                        <td><?=$good['goods_nums']?></td>
                        <td><?=$good['goods_virtual_sales']?></td>
                        <td><?=$good['goods_market']?></td>
                        <td><?=$good['goods_price']?></td>
                        <td><?=$good['goods_promote']?></td>
                        <td><?=$good['goods_is_new']==3?'是':'否'?></td>
                        <td><?=$good['goods_is_promote']==3?'是':'否'?></td>
                        <td><?=$good['goods_is_hot']==3?'是':'否'?></td>
                        <td><?=$good['goods_is_warranty']==1?'是':'否'?></td>
                        <td><?=$good['goods_is_shipping']==1?'是':'否'?></td>
                        <td>
                            <a href="/item/edititem?gid=<?=$good['goods_id']?>"  class="btn btn-mini"><i class="icon-pencil"></i></a>
                            <a href="javascript:void(0);" class="btn btn-mini item-del"><i class="icon-trash"></i></a>
                        </td>
                    </tr>
                <?php endforeach;?>
            </tbody>
        </table>
        <p><a href="javascript:void(0);"  class="btn btn-mini btn-primary" id="del-chk">删除所选</a></p>
        <?php echo $page;?>
    </div>
</div>
<script >
    seajs.config({
        base : "<?php echo $this->di['sysconfig']['staticServer'];?>js/",
        alias : {
            'chkAll' : 'utils/chkAll'
        }
    });
    seajs.use("<?php echo $this->di['sysconfig']['staticServer'];?>js/modules/item/index");
</script>

