<div class="page-header">
    <h1>
        <a href="/tags">标签管理</a>
    </h1>
</div>
<div id = "yunduo-error-msg">

</div>
<div class="row-fluid">
    <div class="span12 pull-left alert" >
        <div class="form-search pull-left">
                   <span class="input-icon">
                        <input type="text" style="width: 120px;margin:0 0 0 5px;" autocomplete="off" id="tags-name"　class="input-small nav-form-search-input" placeholder="标签名..." value="<?= $this->request->getQuery('tags_name')?>">
                        <i style="padding-left:8px;" class="icon-search nav-search-icon"></i>
                        <i id="form-search-clear" class="icon-remove nav-remove-icon" style="left:auto;right:3px;cursor:pointer;"></i>
                    </span>
                    <button class="btn btn-small btn-success" type="button" id="search">搜索</button>
        </div>
    </div>
</div>
<div class="row-fluid">
    <div class="span12">
        <table class="table table-striped table-bordered table-hover" style="margin-bottom=10px;" id="sample-table-1">
            <thead>
                <tr>
                    <th class="center">
                        <label>
                            <input type="checkbox" id="chk-all">
                            <span class="lbl"></span>
                        </label>
                    </th>
                    <th>   标签名    </th>
                    <th>   标签数量    </th>
                    <th >  添加时间    </th>
                    <th >  操作   </th>
                </tr>
            </thead>
            <tbody>
            <?php foreach ($tags as $tag):?>
                <tr>
                    <td class="center"><input type="hidden" class="tag-id" value="<?=$tag['tags_id']?>" /><label><input type="checkbox" class="chk-item" value="<?=$tag['tags_id']?>"/><span class="lbl"></span></label></td>
                    <td class='tag-name'><?=$tag['tags_name']?></td>
                    <td><?=$tag['tags_nums']?></td>
                    <td><?=date('Y-m-d', $tag['tags_addtime'])?></td>
                    <td>
                      <a href="javascript:void(0)"  class="btn btn-mini tags-edit"><i class="icon-pencil"></i></a>
                      <a href="javascript:void(0)"  class="btn btn-mini tags-del"><i class="icon-trash"></i></a>
                    </td>
                </tr>
            <?php endforeach;?>
            </tbody>
        </table>
        <p><a href="javascript:void(0);"  class="btn btn-mini btn-primary" id="del-chk">删除所选</a></p>
        <?php echo $page;?>
    </div>
</div>
</div>
</div>
<script >
    seajs.config({
        base : "<?php echo $this->di['sysconfig']['staticServer'];?>js/",
        alias : {
            'chkAll' : 'utils/chkAll'
        }
    });
    seajs.use("<?php echo $this->di['sysconfig']['staticServer'];?>js/modules/tags/main");
</script>

