<div class="w auto">
    <div class="crumbs-nav"><a href="#">首页</a>
        <em>></em><a href="#">订单中心</a>
        <em>></em><a href="#">售后服务</a>
        <em>></em><a href="#">售后进度</a>
    </div>
    <div class="content ovh">
        <?php $this->partial("common/nav") ?>
        <div class="main fl dib">
            <div class="info-tit rel">
                <h2 class="tit dib">售后进度</h2>
            </div>
            <div class="order">
                <div class="after-sale-tit fix">
                    <ul>
                        <li class="col-1">订单编号：<?=$supportInfo['bord_sn']?></li>
                        <li class="col-2">状态：
                            <?php if(in_array($supportInfo['bord_status'], [1, 3, 11])) echo '进行中';?>
                            <?php if($supportInfo['bord_status'] == 5) echo '审核未通过';?>
                            <?php if($supportInfo['bord_status'] == 7) echo '已解决';?>
                            <?php if(in_array($supportInfo['bord_status'], [9, 13])) echo '已关闭';?>
                        </li>
                        <li class="col-3">申请时间：<?=date('Y-m-d H:i:s', $supportInfo['bord_addtime'])?></li>
                    </ul>
                </div>
                <div class="after-sale-detail">
                    <div class="tit">处理信息</div>
                    <div class="detail-list">
                        <?php foreach($supportLogs as $log):?>
                            <?php if(in_array($log['ord_act_type'], array(11, 13))):?>
                                <div class="row"><p class="feedback-time"><?=date('Y-m-d H:i:s', $log['ord_act_addtime'])?></p>
                                    <p class="ovh"><?=$this->sysconfig['supportProgress'][$log['ord_act_type']][$supportInfo['bord_type']]?>[快递单号:<?=$supportInfo['bord_shipping_sn']?>]</p>
                                </div>
                            <?php else:?>
                            <div class="row"><p class="feedback-time"><?=date('Y-m-d H:i:s', $log['ord_act_addtime'])?></p>
                                <p class="ovh"><?=$this->sysconfig['supportProgress'][$log['ord_act_type']]?></p>
                            </div>
                            <?php endif;?>
                        <?php endforeach;?>
<!--                        <div class="row"><p class="feedback-time">2014-5-22 12:33:44</p><p class="ovh">您提交的售后申请客服将会第一时间为您解决，请耐心等候。</p></div>
                        <div class="row"><p class="feedback-time">2014-5-22 12:33:44</p><p class="ovh">您的今后申请已通过审核，请尽快邮寄童鞋到云朵售后服务部。</p></div>
                        <div class="row"><p class="feedback-time">2014-5-22 12:33:44</p><p class="ovh">很抱歉，由于您的鞋子已经穿过，影响二次销售，您的审核未通过。如有疑议，请与客服联系：
                                <strong class="color">400-9189-400</strong>
                            </p></div>-->
                    </div>
                    <?php if(!in_array($supportInfo['bord_status'], [9, 13])):?>
                    <div class="after-sale-tips" style="<?=$supportInfo['bord_status'] == 7? 'display:none' : '';?>">
                        <img class="dib" src="<?=$this->di['sysconfig']['staticServer']?>images/mall/after-sale-null.jpg" alt="等待处理中">
                        <p>客服正在全力的帮您处理中～请耐心等待～</p>
                    </div>
                <?php endif;?>
                </div>
            </div>
        </div>
    </div>
</div>
