<div class="page-header">
  <h1>
       <a href="/codes/index">云码管理</a>
      <small>
          <i class="icon-double-angle-right"></i>
       生成云码
      </small>
  </h1>
</div>
<div class="row-fluid">
    <div class="span12" >
        <div class="widget-box">
            <div class="widget-header widget-header-blue widget-header-flat">
                <h4 class="lighter">
                 生成云码</h4>
            </div>
        <div id = "yunduo-error-msg">

        </div>
        <?php  if(isset($error)) echo "<script>yunduoErrorShow(" .json_encode(json_decode($error)->msg). ");</script>"; ?>
            <div class="widget-body">
                <div class="widget-main">
          <div class="row-fluid">
            <form id="itemForm"  class="form-horizontal form addCode-form"  action="" method="POST" enctype="multipart/form-data">

            <div class="control-group">
                  <label class="control-label"><small class="text-error"> * </small> 数量</label>
                  <div class="controls">
                    <input type="text" name="num" class=""  value="<?php echo $this->request->get('num');?>" />
                    <span class="help-inline"></span>
                  </div>
            </div>
            <div class="control-group">
                  <label class="control-label"><small class="text-error"> * </small> 指定商品id</label>
                  <div class="controls">
                    <input type="text" name="gid" class=""  value="<?php echo $this->request->get('gid');?>"/>
                    <span class="help-inline">0，表示所有商品可用，否则将是指定商品id的集合用逗号隔开，如：
            1,2,3,4',</span>
                  </div>
            </div>
            <div class="control-group">
                 <label class="control-label"><small class="text-error" class="required" > * </small> 类型 </label>
                    <div class="controls">
                 <select name="type">
                    <option class="change_op" value="1" <?php if($this->request->get('type') == '1') echo 'selected="selected"'?>>普通</option>
                    <option class="change_op" value="3"<?php if($this->request->get('type') == '3') echo 'selected="selected"'?>>免费</option>
                </select>
                 </div>
            </div>

            <div class="control-group">
                  <label class="control-label"><small class="text-error"> * </small> 有效期开始时间</label>
                  <div class="controls">
                    <input type="text"  name="starTime"   id ="start_uploadtime" class="required"   value="<?php echo $this->request->get('starTime');?>" />
                    <span class="help-inline"></span>
                  </div>
            </div>
            <div class="control-group">
                  <label class="control-label"><small class="text-error"> * </small> 有效期结束时间 </label>
                  <div class="controls">
                    <input type="text"  name="endTime"  id="end_uploadtime" class="required"  value="<?php echo $this->request->get('endTime');?>"/>
                    <span class="help-inline"></span>
                  </div>
            </div>
                <button type="submit" id="form_submit" class="btn">确认提交</button>
                </form>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
<script >
    seajs.use("<?php echo $this->di['sysconfig']['staticServer'];?>js/modules/codes/main");
    seajs.use("<?php echo $this->di['sysconfig']['staticServer'];?>js/spm_modules/jquery-plugin/jquery.validate.js");
    seajs.use("<?php echo $this->di['sysconfig']['staticServer'];?>js/modules/coupons/couponsValidate");
</script>