
<div class="page-header">
    <h1>
        <a href="/codes">云码管理</a>
        <span class="pull-right">
            <a href="/codes/addcode">
                <button class="btn btn-small"><i class="icon-plus"></i>添加云码</button>
            </a>
        </span>
    </h1>
</div>
<div class="row-fluid alert">
    <div class="span10">
        <div class="form-search pull-left">
        <form action="" method="get" accept-charset="utf-8" >
           <span>云码：</span>
           <span class="input-icon">
                <input type="text"  autocomplete="off" name="code" id="form-search-input" class="input-big nav-form-search-input" placeholder="搜索..." value="<?php echo $this->request->get('code'); ?>">
                <i style="padding-left:8px;" class="icon-search nav-search-icon"></i>
                <i id="form-search-clear" class="icon-remove nav-remove-icon" style="left:auto;right:3px;cursor:pointer;"></i>
            </span>
           开始时间： <input type="text"  name="starTime"   id ="start_uploadtime" class="required" value="<?php echo $this->request->get('starTime'); ?>" />
           结束时间：<input type="text"  name="endTime"  id="end_uploadtime" class="required"  value="<?php echo $this->request->get('endTime'); ?>" />
           类型：
         <select id="form-search-field-select" style="width: 110px;" name ='type'>
         <option value="1" <?php if($this->request->get('type') == '1') echo 'selected="selected"';?>>普通</option>
         <option value="3" <?php if($this->request->get('type') == '3') echo 'selected="selected"';?>>免费</option>
         <option value="0" <?php if($this->request->get('type') == '0') echo 'selected="selected"';?>>全部</option>
           </select>
                      状态：
         <select id="form-search-field-select" style="width: 110px;" name="status">
         <option value="1" <?php if($this->request->get('status') == '1') echo 'selected="selected"';?>>可用</option>
         <option value="3" <?php if($this->request->get('status') == '3') echo 'selected="selected"';?>>禁用</option>
         <option value="0" <?php if($this->request->get('status') == '0') echo 'selected="selected"';?>>全部</option>
           </select>
            <input type="submit" name="" value="搜索" class="btn btn-small" >
            </form>
        </div>

    </div>
</div>
<div class="row-fluid">
    <div class="span12">
        <table class="table table-striped table-bordered table-hover" style="margin-bottom=10px;" id="sample-table-1">
            <thead>
                <tr>
                    <th class="center">
                        <label>
                            <input type="checkbox" id="chk-all">
                            <span class="lbl"></span>
                        </label>
                    </th>
                    <th class="center">   ID </th>
                    <th>   云码    </th>
                    <th>   类型    </th>
                    <th >  指定商品ID    </th>
                    <th >有效期开始时间</th>
                    <th >有效期结束时间</th>
                    <th> 使用时间 </th>
                    <th> 状态</th>
                    <th> 生成时间</th>
<!--                     <th> 操作</th> -->
                </tr>
            </thead>
            <tbody>
            <?php foreach($codelist as $v):?>
             <tr>
                    <td class="center"><label><input type="checkbox"  class="chk-item"  value="<?php echo $v['yc_id'];?>"/> <span class="lbl"></span></label></td>
                    <td class="center"><?php echo $v['yc_id'];?><input type="hidden" class="ycid" value="<?php echo $v['yc_id'];?>"></td>
                    <td><?php echo $v['yc_ctx'];?></td>
                    <td><?php echo $v['yc_type']=='1'?'普通':'免费';?></td>
                    <td><?php echo $v['yc_good_ids']?></td>
                    <td><?php echo date('Y-m-d H:i:s',$v['yc_start_time'])?></td>
                    <td><?php echo date('Y-m-d H:i:s',$v['yc_end_time'])?></td>
                    <td class="uid<?php echo $v['yc_id'];?>"><?php echo !empty($v['yc_used_time'])?date('Y-m-d H:i:s',$v['yc_used_time']):'未使用';?> </td>
                    <td class="status<?php echo $v['yc_id'];?>"> <?php echo $v['yc_status'] == '1'?'可用':'禁用';?> <input type="hidden"  value="<?php echo $v['yc_status'];?>" /></td>
                    <td><?php echo date('Y-m-d H:i:s',$v['yc_addtime'])?></td>
<!--                     <td> <a href="javascript:void(0)" class="btn btn-mini attr_edit" data="<?php echo $v['yc_id'];?>">属性编辑</a> </td> -->
                </tr>
            <?php endforeach;?>
            </tbody>
        </table>
        <p>
        <span>
            状态：
         <select id="update-select" style="width: 110px;" name="status" >
         <option value="1" <?php if($this->request->get('status') == '1') echo 'selected="selected"';?>>可用</option>
         <option value="3" <?php if($this->request->get('status') == '3') echo 'selected="selected"';?>>禁用</option>
           </select></span>
        <a href="javascript:void(0);"  class="btn btn-mini" id="dosubmit">提交</a></p>
        <?php echo $page;?>
    </div>
</div>
</div>
</div>
<script >
    seajs.config({
        base : "<?php echo $this->di['sysconfig']['staticServer'];?>js/",
        alias : {
            'chkAll' : 'utils/chkAll'
        }
    });
    seajs.use("<?php echo $this->di['sysconfig']['staticServer'];?>js/modules/codes/main");
    seajs.use("<?php echo $this->di['sysconfig']['staticServer'];?>js/modules/codes/index.js");
</script>

