<div>
    <div class="page-header">
        <h1>
            <a href="/shipping">快递费用规则管理</a>
        </h1>
    </div>

    <div id = "yunduo-error-msg"></div>

    <div class="row-fluid">
        <div class="span12">
            <form id="ship-form" action="/shipping" method="get" class="alert alert-block" style="padding: 20px;">
                <select id="provinces" name="pro_id" class="required" data="<?php echo $this->request->get('pro_id');?>"></select>
                <select id="cities" name="city_id" class="" data="<?php echo $this->request->get('city_id');?>"> </select>
                <select id="districts" name="dis_id" class="" data="<?php echo $this->request->get('dis_id');?>"> </select>
                <input placeholder="快递费用" type="text" name="shipping_pay" id="fee" class="{required:true,digits:true,max:127}" value="<?php echo $this->request->get('shipping_pay');?>">
                <a href="javascript:void(0);" class="btn btn-mini" id="add-rule"><i class="icon-plus"></i>添加</a>
                <a class="btn btn-mini" id="search"><i class="icon-search"></i>搜索</a>
                <span class="valid_error" style="display: none;" id="bk-error"></span>
            </form>
            <table class="table table-striped table-bordered table-hover table-condensed" style="margin:10px 0;" id="ship-tb">
                <thead>
                <tr class="center">
                    <th class="center"><label><input type="checkbox" id="chk-all"><span class="lbl"></span></label></th>
                    <th class="center"> 省份</th>
                    <th class="center"> 城市</th>
                    <th class="center"> 县区</th>
                    <th class="center"> 快递费用</th>
                    <th class="center"> 操作</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach($rules as $key=>$rule):?>
                    <tr>
                        <td class="center"><label><input type="checkbox" class="chk-item"/> <span class="lbl"></span></label></td>
                        <td class="center pro" data="<?php echo $rule['pro_id'];?>"><?php echo $rule['pro_name'];?></td>
                        <td class="center city" data="<?php echo $rule['city_id'];?>"><?php if(!$rule['city_name']) echo '-'; else echo $rule['city_name'];?></td>
                        <td class="center dis" data="<?php echo $rule['dis_id'];?>"><?php if(!$rule['dis_name']) echo '-'; else echo $rule['dis_name'];?></td>
                        <td class="center fee"><?php echo $rule['shipping_pay'];?></td>
                        <td class="center">
                            <a href="javascript:void(0)" class="btn btn-mini edit"><i class="icon-pencil"></i></a>
                            <a href="javascript:void(0)" class="btn btn-mini delete"><i class="icon-trash"></i></a>
                        </td>
                    </tr>
                <?php endforeach;?>
                </tbody>
            </table>
            <p>
                <button class="btn btn-primary btn-mini" id="del-rules">
                    <i class="icon-trash"></i>
                    删除选中
                </button>
            </p>
            <p><?php echo $page;?></p>
        </div>
    </div>
</div>
<script>
    seajs.config({
        base : "<?php echo $this->di['sysconfig']['staticServer'];?>js/",
        alias:{
            'region' : 'utils/region',
            'chkAll' : 'utils/chkAll'
        }
    });
    seajs.use(['modules/shipping/main', 'spm_modules/jquery-plugin/jquery.validate', 'spm_modules/jquery-plugin/jquery.validate.metadata', 'modules/shipping/shipValidate']);
</script>