<div>
    <div class="page-header">
        <h1>
            <a href="/order">订单管理</a>
            <small>
                <i class="icon-double-angle-right fa fa-angle-double-right"></i>
                添加订单
            </small>
        </h1>
    </div>

    <div id = "yunduo-error-msg"></div>

<!--添加商品可用标志，1为可添加，3为不可添加-->
<input type="hidden" id="add-flag" value="3">
    <div class="row-fluid page-header">

    <div class="row-fluid">
        <div class="span12">
            <table class="table table-striped table-bordered table-hover" style="margin-bottom=10px;" id="add-order-tb">
                <thead>
                <tr>
                    <th class="center">商品名称</th>
                    <th class="center">商品属性</th>
                    <th class="center">数量</th>
                    <th class="center">市场价</th>
                    <th class="center">单价</th>
                    <th class="center">操作</th>
                </tr>
                </thead>
                <tbody class ="order-goods-body">
                    <tr class="order-goods-info">
                        <input type="hidden" class="goods-id" value="">
                        <td class="center display-name"><input type="text" class="goods-name" value=""><a href="javascript:void(0)" class="btn btn-mini check-goods">确定</a></td>
                        <td class="center">颜色:<span class="goods-color">--</span>，尺码:<span class="goods-size">--</span></td>
                        <td class="center show-goods-num"><input type="text" class="goods-num" value="1" style="width:100px;"></td>
                        <td class="center market-price">--</td>
                        <td class="center show-goods-price">--</td>
                        <td class="center operate-btn">
                          <a href="javascript:void(0)"  class="btn btn-mini goods-makesure">确认添加</a>
                          <a href="javascript:void(0)"  class="btn btn-mini goods-del" data="1">删除</a>
                        </td>
                    </tr>
                    <tr class="add-goods" style="display:none">
                        <input type="hidden" class="goods-id" value="">
                        <td class="center display-name"><input type="text" class="goods-name" value=""><a href="javascript:void(0)" class="btn btn-mini check-goods">确定</a></td>
                        <td class="center">颜色:<span class="goods-color">--</span>，尺码:<span class="goods-size">--</span></td>
                        <td class="center show-goods-num"><input type="text" class="goods-num" value="1" style="width:100px;"></td>
                        <td class="center market-price">--</td>
                        <td class="center show-goods-price">--</td>
                        <td class="center operate-btn">
                          <a href="javascript:void(0)" class="btn btn-mini goods-makesure">确认添加</a>
                          <a href="javascript:void(0)" class="btn btn-mini goods-del" data="1">删除</a>
                        </td>
                    </tr>
                </tbody>
            </table>
            <a href="javascript:void(0)" class="btn btn-mini" id="add-goods-btn"><i class="icon-plus"></i>继续添加商品</a>
        </div>
    </div>
    <div class="row-fluid">
        <form id="add-order-form">
        <div class="span6">
            <ul class="unstyled list-striped pricing-table-header order-info">
                <li>联系人姓名：<input type="text" id="consignee" value="" name="consignee" class="{required:true, maxlength:60}"></li>
                <li>联系人手机：<input type="text" id="mobi" value="" name="mobi" class="{required:true, mobile:true}"></li>
                <li>配送地址：
                  <span id="region-selector">
                      <select id="provinces" style='width:130px'></select>
                      <select id="cities" style='width:130px'></select>
                      <select id="districts" style='width:130px'></select>
                      <select id="streets" style='width:130px'></select>
                  </span>
                </li>
                <li>详细地址：<input type="text" id="addr" value=""></li>
                <li>
                    操作备注： <textarea id="desc" style="width: 313px;" class="vat" rows="5"></textarea>
                </li>
            </ul>
        </div>
        <div class="span6">
            <ul class="unstyled list-striped pricing-table-header" style="text-align:left;">
                <li>快递费：<input type="text" id="shipping-fee" value="" name="shipping-fee" class="{required:true,number:true}"></li>
                <li>总计金额：<span id="order-total-fee">0</span></li>
                <li>实付金额：<input type="text" id="order-pay-fee" value="0" name="order-pay-fee" class="{required:true, number:true}"></li>
            </ul>
        </div>
        </form>
    </div>
            <a href="javascript:void(0)" class="btn btn-mini edit-status" id="create-order">生成订单</a>
            <a href="/order" class="btn btn-mini">取消</a>
</div>

<script >

    seajs.config({
        base : "<?php echo $this->di['sysconfig']['staticServer'];?>js/",
        alias:{
            'region' : 'utils/region'
        }
    });
    seajs.use(['modules/order/addorder', 'spm_modules/jquery-plugin/jquery.validate', 'spm_modules/jquery-plugin/jquery.validate.metadata', 'modules/order/addValidate'] );
</script>