<div>
    <div class="page-header">
        <h1>
            <a href="/order">订单管理</a>
            <small>
                <i class="icon-double-angle-right fa fa-angle-double-right"></i>
                订单详情
            </small>
        </h1>
    </div>

    <div class="row-fluid page-header">
        <div class="span12" style="text-align: center">

            订单详情

        </div>

    </div>

    <div id = "yunduo-error-msg"></div>

    <?php if(!empty($orderInfo)) : ?>
    <div class="row-fluid page-header">
        <div class="span4" style="text-align: center">

            订单号：<?=$orderInfo['order_sn']?>

        </div>
        <div class="span4" style="text-align: center">

            下单时间：<?=date('Y-m-d H:i:s', $orderInfo['order_addtime']);?>

        </div>
        <div class="span4" style="text-align: center">

            订单状态：<?php switch ($orderInfo['order_status']) {case '1':echo '交易成功,';break;case '3':echo '交易关闭,';break;}?>
            <?php switch ($orderInfo['order_pay_status']) {case '1':echo '未付款';break;case '3':echo '已付款';break;case '5':echo '申请退款中';break;case '7':echo '退款成功';break;}?>,
            <?php switch ($orderInfo['order_delivery_status']) {case '1':echo '未发货';break;case '3':echo '已发货';break;}?>

        </div>

        <input type="hidden" id="order-id" value="<?=$orderInfo['order_id']?>">

    </div>
    <div class="row-fluid">
        <div class="span12">
            <table class="table table-striped table-bordered table-hover" style="margin-bottom=10px;" id="sample-table-1">
                <thead>
                <tr>
                    <th class="center">商品名称</th>
                    <th class="center">商品货号</th>
                    <th class="center">售价</th>
                    <th class="center">商品属性</th>
                    <th class="center">数量</th>
                    <th class="center">是否赠品或者配件</th>
                    <th class="center">已售后</th>
                    <th class="center">操作</th>
                </tr>
                </thead>
                <tbody>
                <?php if(isset($orderGoods) && !empty($orderGoods)) : ?>
                    <?php foreach ($orderGoods as $data) : ?>
                        <tr>
                            <input type="hidden" class='order-goods-id' value="<?=$data['ord_goods_id']?>">
                            <input type="hidden" class='goods-id' value="<?=$data['goods_id']?>">
                            <td class="center"><?=$data['goods_name']?></td>
                            <td class="center"><?=$data['goods_sn']?></td>
                            <td class="center goods-price"><?=$data['ord_goods_price']?></td>
                            <td class="center">颜色:<span class="goods-attr2" data="<?php echo json_decode($data['attrs_info'], true)[0]['id']?>"><?php echo json_decode($data['attrs_info'], true)[0]['name']?></span>尺码:<span class="goods-attr1" data="<?php echo json_decode($data['attrs_info'], true)[1]['id']?>"><?php echo json_decode($data['attrs_info'], true)[1]['name']?></span></td>
                            <td class="center goods-num"><?=$data['ord_goods_num']?></td>
                            <td class="center"><?php echo $data['ord_goods_type'] == '1' ? '否' : '是'?></td>
                            <td class="center"><?php echo $data['ord_goods_back'] == '1' ? '否' : '是'?></td>
                            <td class="center"><a href="javascript:void(0)"  class="btn btn-mini goods-edit" data="<?=$data['order_id']?>-<?=$data['goods_id']?>">修改产品</a></td>
                        </tr>
                    <?php endforeach;?>
                <?php else : ?>
                    找不到对应商品
                <?php endif; ?>
                </tbody>
            </table>
        </div>
    </div>
    <div class="row-fluid">
        <form id="detail-form">
        <div class="span6">
            <ul class="unstyled list-striped pricing-table-header order-info">
                <li>支付方式：<?php switch ($orderInfo['order_pay_type']) {case '1':echo '支付宝';break;case '3':echo '微信支付';break;case '5':echo '货到付款';break;case '7':echo '信用卡';break;case '9':echo '储蓄卡';break;}?></li>
                <li>联系人姓名：<span class="consignee"><?=$orderInfo['order_consignee'] ?></span></li>
                <li>联系人手机：<span class="mobi"><?php echo $orderInfo['order_mobile'] != '' ? $orderInfo['order_mobile'] : $orderInfo['order_tel']?></span></li>
                <li>配送地址：
            <span id="region-selector" style="display:none;">
                <select id="provinces" data="<?=$orderInfo['order_province']?>"></select>
                <select id="cities" data="<?=$orderInfo['order_city']?>"></select>
                <select id="districts" data="<?=$orderInfo['order_district']?>"></select>
                <select id="streets" data="<?=$orderInfo['order_street']?>"></select>
            </span>
            <span class="region-display" style="display:block;">
                <span class="order-province"></span>&nbsp;<span class="order-city"></span>&nbsp;<span class="order-district"></span>&nbsp;<span class="order-street"></span>
            </span><span class="addr"><?=$orderInfo['order_addr']?></span></li>
                <li >快递方式:<span class="shipping-type" data="<?=$orderInfo['order_shipping_type']?>"><?php switch ($orderInfo['order_shipping_type']) {case '1':echo '快递';break;case '3':echo '自取';break;}?></span></li>
                <li>用户备注：<?=$orderInfo['order_buyer_msg']?></li>
                <?php if($orderInfo['order_is_inv'] == 1):?>
                   <li>
                        <p>发票类型:<?=$orderInfo['order_inv_type'] == 1 ? '公司' : '个人'?></p>
                        <p>发票抬头:<?=$orderInfo['order_inv_title']?></p>
                    </li>
              <?php endif;?>
            </ul>
        </div>
        <div class="span6">
            <ul class="unstyled list-striped pricing-table-header" style="text-align:left;">
                <li>快递费：<em style="color:red"><?=$orderInfo['order_shipping_fee']?></em></li>
                <li>总计金额：<em style="color:red"><?=$orderInfo['order_total']?></em></li>
                <li>实付金额：<em style="color:red"><?=$orderInfo['order_paied']?></em></li>
                <li>物流信息：<?=$orderInfo['order_shipping_name']?>（<?=$orderInfo['order_shipping_sn']?>）</li>
                <li><a href="javascript:void(0)"  class="btn btn-mini order-edit" data="<?=$orderInfo['order_id']?>"><i class="icon-pencil"></i>修改信息</a></li>
            </ul>
        </div>
        </form>
    </div>
    <div class="row-fluid">
        可执行操作：
        <?php if($orderInfo['order_status'] == 0 && $orderInfo['order_pay_status'] == 1 && $orderInfo['order_delivery_status'] == 1) : ?>
            <a href="javascript:void(0)" class="btn btn-mini edit-status" operate="invalid">订单失效</a>
        <?php elseif($orderInfo['order_status'] == 0 && $orderInfo['order_pay_status'] == 3 && $orderInfo['order_delivery_status'] == 1) : ?>
            <a href="javascript:void(0)" class="btn btn-mini edit-status" operate="applyBack">申请退款</a>
            <a href="javascript:void(0)" class="btn btn-mini edit-status" operate="deliver">去发货</a>
        <?php elseif($orderInfo['order_status'] == 0 && $orderInfo['order_pay_status'] == 3) : ?>
            <a href="javascript:void(0)" class="btn btn-mini edit-status" operate="orderSuccess">交易成功</a>
            <a href="javascript:void(0)" class="btn btn-mini edit-status" operate="applyBack">申请退款</a>
        <?php elseif($orderInfo['order_status'] == 0 && $orderInfo['order_pay_status'] == 7 && ($orderInfo['order_delivery_status'] == 1 || $orderInfo['order_delivery_status'] == 3)) : ?>
            <a href="javascript:void(0)" class="btn btn-mini edit-status" operate="orderClose">交易关闭</a>
        <?php endif;?>
    </div>
</div>
<div class="log-area mt">
    <table class="table table-striped table-bordered table-hover">
        <thead>
        <tr>
            <th class="center">操作者</th>
            <th class="center">操作内容</th>
            <th class="center">操作时间</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach($orderLogs as $log):?>
            <tr>
                <td class="center"><?=$log['ord_act_uname']?></td>
                <td class="center"><?=$log['ord_act_info']?></td>
                <td class="center"><?php echo date('Y-m-d H:i:s',$log['ord_act_addtime']);?></td>
            </tr>
        <?php endforeach;?>
        </tbody>
    </table>
</div>
<?php else : ?>
    没有此订单
<?php endif; ?>

<script >

    seajs.config({
        base : "<?php echo $this->di['sysconfig']['staticServer'];?>js/",
        alias:{
            'region' : 'utils/region'
        }
    });
    seajs.use(["modules/order/main", 'spm_modules/jquery-plugin/jquery.validate', 'spm_modules/jquery-plugin/jquery.validate.metadata', 'modules/order/detailValidate']);
</script>