<div>
    <div class="page-header">
        <h1>
            <a href="/order">订单管理</a>
            <span class="pull-right">
                <a href="/order/addorder">
                    <button class="btn btn-small"><i class="icon-plus"></i>添加订单</button>
                </a>
            </span>
        </h1>
    </div>
    <div id = "yunduo-error-msg"></div>
    <div class="row-fluid">
        <div class="span12">
            <div>
        <form method="get" action="/order" id="order-search-form" class="alert" style="padding: 15px 15px;">
            <input type="text" placeholder="订单编号" id="order-sn" value="<?php echo $this->request->get('order_sn');?>" name="order_sn">
                <input type="text" placeholder="收货人姓名" id="order-consignee" value="<?php echo $this->request->get('order_consignee');?>" name="order_consignee">
                <input type="text" placeholder="下单用户手机" id="u-mobi" value="<?php echo $this->request->get('u_mobi');?>" name="u_mobi">
                <input type="text" placeholder="快递单号" id="shipping-sn" value="<?php echo $this->request->get('order_shipping_sn');?>" name="order_shipping_sn">
                <select id="order-status" style="width: 150px;" name="orderStatus" data="<?php echo $this->request->get('orderStatus');?>">
                    <option value="0">订单状态</option>
                    <option value="1">交易成功</option>
                    <option value="3">交易关闭</option>
                    <option value="5">待付款</option>
                    <option value="7">待发货</option>
                    <option value="9">已付款</option>
                    <option value="11">已发货</option>
                    <option value="13">退款中</option>
                    <option value="15">退款成功</option>
                </select>
            <script>
                var initSel = function(sel){
                    $('#'+sel+' option[value='+($('#'+sel).attr('data') ? $('#'+sel).attr('data') : 0)+']').attr('selected', 'selected');
                }
                initSel('order-status');
            </script>
                <input type="text" placeholder="开始时间" id="start-time" value="<?php echo $this->request->get('start_time');?>" name="start_time">&nbsp;-
                <input type="text" placeholder="结束时间" id="end-time" value="<?php echo $this->request->get('end_time');?>" name="end_time">
            <a class="btn btn-mini" id="search"><i class="icon-search"></i>搜索</a>
        </form>
        </p>
        </div>
        <table class="table table-striped table-bordered table-hover table-condensed" style="margin-bottom=10px;" id="sample-table-1">
            <thead>
                <tr>
                    <th class="center"><label><input type="checkbox" id="chk-all"><span class="lbl"></span></label></th>
                    <th class="center">   订单编号 </th>
                    <th class="center">   收货人    </th>
                    <th class="center">   下单用户手机    </th>
                    <th class="center">   快递单号    </th>
                    <th class="center">  总金额    </th>
                    <th class="center">  实付金额   </th>
                    <th class="center">  订单状态   </th>
                    <th class="center">   下单时间    </th>
                    <th class="center">  操作   </th>
                </tr>
            </thead>
            <tbody>
            <?php if(empty($list)):?>
                暂无订单信息哦！！！！
            <?php else:?> 
                <?php foreach ($list as $data):?>
                <tr>
                    <input type="hidden" class="order-id" value="<?=$data['order_id']?>" />
                    <td class="center"><label><input type="checkbox" class="chk-item"/> <span class="lbl"></span></label></td>
                    <td class="data_id center"><?=$data['order_sn']?></td>
                    <td class="center"><?=$data['order_consignee']?></td>
                    <td class="center"><?=$data['u_mobi']?></td>
                    <td class="center"><?=$data['order_shipping_sn']?></td>
                    <td class="center"><?=$data['order_total']?></td>
                    <td class="center"><?=$data['order_paied']?></td>
                    <td class="center">
                        <?php switch ($data['order_status']) {case '1':echo '未确认收货,';break;case '3':echo '已确认收货,';break;case '5':echo '失效,';break;case '7':echo '取消,';break;case '9':echo '已分单,';break;case '11':echo '交易成功,';break;}?>
                        <?php switch ($data['order_pay_status']) {case '1':echo '未付款';break;case '3':echo '已付款';break;case '5':echo '申请退款中';break;case '7':echo '退款成功';break;}?>,
                        <?php switch ($data['order_delivery_status']) {case '1':echo '未发货';break;case '3':echo '已发货';break;case '5':echo '已收货';break;}?></td>
                    <td class="center"><?=date('Y-m-d H:i:s',$data['order_addtime'])?></td>
                    <td class="center">
                      <a href="/order/detail?orderId=<?=$data['order_id']?>"  class="btn btn-mini order_edit"><i class="icon-pencil"></i></a>
                    </td>
                </tr>
                <?php endforeach;?>
            <?php endif;?>
            </tbody>
        </table>
            <a href="javascript:void(0)" class="btn btn-mini batch-edit-order" operate="batchInvalid" des="订单失效">订单失效</a>
            <a href="javascript:void(0)" class="btn btn-mini batch-edit-order" operate="batchDeliver" des="发货">去发货</a>
            <a href="javascript:void(0)" class="btn btn-mini batch-edit-order" operate="batchApplyBack" des="申请退款">申请退款</a>
            <a href="javascript:void(0)" class="btn btn-mini batch-edit-order btn-success" operate="batchOrderSuccess" des="交易成功"><i class="icon-ok"></i>交易成功</a>
            <a href="javascript:void(0)" class="btn btn-mini batch-edit-order btn-primary" operate="batchOrderClose" des="交易关闭"><i class="icon-remove"></i>交易关闭</a>
        <p><?php echo $page;?></p>
    </div>
</div>
</div>
<script>
    seajs.config({
        base : "<?php echo $this->di['sysconfig']['staticServer'];?>js/",
        alias:{
            'chkAll' : 'utils/chkAll',
            'calendar' : 'utils/calendar'
        }
    });
    seajs.use('modules/order/index');
</script>