<div>
    <div class="page-header">
        <h1>
            <a href="/back">退换货管理</a>
            <span class="pull-right">
                <a href="/back/add">
                    <button class="btn btn-small"><i class="icon-plus"></i>添加</button>
                </a>
            </span>
        </h1>
    </div>
    <div class="row-fluid">
        <div class="span12">
                <form method="get" action="/back" id="back-form" class="alert alert-block" style="padding: 20px;">
                <span class="input-icon">
                    <input id="bord-sn" class="input-big nav-form-search-input" type="text" value="<?php echo $this->request->get('bord_sn');?>" placeholder="售后编号..." name="bord_sn" autocomplete="off">
                    <i class="icon-search nav-search-icon" style="padding-left:8px;top:0;"></i>
                    <i id="search-clear-bord" class="icon-remove nav-remove-icon" style="display: none;;left:auto;right:3px;cursor:pointer;top:0;"></i>
                </span>
                <span class="input-icon">
                    <input id="order-sn" class="input-big nav-form-search-input" type="text" value="<?php echo $this->request->get('order_sn');?>" placeholder="订单编号..." name="order_sn" autocomplete="off">
                    <i class="icon-search nav-search-icon" style="padding-left:8px;top:0;"></i>
                    <i id="search-clear-order" class="icon-remove nav-remove-icon" style="display:none;left:auto;right:3px;cursor:pointer;top:0;"></i>
                </span>
                <input type="text" placeholder="开始时间" id="start-time" value="<?php echo $this->request->get('start_time');?>" name="start_time">&nbsp;-
                <input type="text" placeholder="结束时间" id="end-time" value="<?php echo $this->request->get('end_time');?>" name="end_time">
                    <?php $bordType = $this->request->get('start_time')?:0;?>
                <select id="bord-type" style="width: 160px;" name="bord_type" data="<?php echo $this->request->get('bord_type');?>">
                    <option value="0">申请类型</option>
                    <option value="1">退货</option>
                    <option value="3">换货</option>
                    <!--<option value="5" >退款</option>-->
                    <option value="5">智能模块更换</option>
                </select>
                <select id="bord-status" style="width: 160px;" name="bord_status" data="<?php echo $this->request->get('bord_status');?>">
                    <option value="0">状态</option>
                    <option value="1">未审核</option>
                    <option value="3">审核通过</option>
                    <option value="5">审核未通过</option>
                    <option value="7">完成</option>
                    <option value="9">关闭</option>
                </select>
                <select id="bord-reason" style="width: 160px;" name="bord_reason" data="<?php echo $this->request->get('bord_reason');?>">
                    <option value="0">申请原因</option>
                    <option value="1">尺码原因</option>
                    <option value="2">快递原因</option>
                    <option value="3">鞋体原因</option>
                    <option value="4">智能模块原因</option>
                    <option value="5">发错货</option>
                    <option value="6">其他</option>
                </select>
                <script>
                    var initSel = function(sel){
                        $('#'+sel+' option[value='+($('#'+sel).attr('data') ? $('#'+sel).attr('data') : 0)+']').attr('selected', 'selected');
                    }
                    initSel('bord-type');
                    initSel('bord-status');
                    initSel('bord-reason');
                </script>
                <a href="javascript:void(0);"  class="btn btn-mini" id="search"><i class="icon-search"></i>搜索</a>
                </form>
            <table class="table table-striped table-bordered table-hover table-condensed" style="margin-bottom=10px;" id="sample-table-1">
                <thead>
                <tr>
                    <th class="center"><label><input type="checkbox" id="chk-all"><span class="lbl"></span></label></th>
                    <th class="center">   售后编号 </th>
                    <th class="center">   订单编号    </th>
                    <th class="center">  申请类型   </th>
                    <th class="center">  申请原因   </th>
                    <th class="center">  状态   </th>
                    <th class="center">   申请时间    </th>
                    <th class="center">  操作   </th>
                </tr>
                </thead>
                <tbody>
                <?php if(empty($list)):?>
                    没有售后订单哦！！！！
                <?php else:?>
                    <?php foreach ($list as $data):?>
                        <tr>
                            <td class="center"><label><input type="checkbox" class="chk-item" value="<?=$data['bord_id']?>"/> <span class="lbl"></span></label></td>
                            <td class='data_id center'><?=$data['bord_sn']?></td>
                            <td class="center"><?=$data['order_sn']?></td>
                            <td class="center">
                                <?php
                                if($data['bord_type'] == 1) echo '退货';
                                else if($data['bord_type'] == 3) echo '换货';
                                //else if($data['bord_type'] == 5) echo '退款';
                                else if($data['bord_type'] == 5) echo '智能模块更换';

                                ?>
                            </td>
                            <td class="center">
                                <?php
                                if($data['bord_reason'] == 1) echo '尺码原因';
                                else if($data['bord_reason'] == 2) echo '快递原因';
                                else if($data['bord_reason'] == 3) echo '鞋体原因';
                                else if($data['bord_reason'] == 4) echo '智能模块原因';
                                else if($data['bord_reason'] == 5) echo '发错货';
                                else if($data['bord_reason'] == 6) echo '其他';
                                ?>
                            </td>
                            <td class="center">
                                <?php
                                if($data['bord_status'] == 1) echo '未审核';
                                else if($data['bord_status'] == 3) echo '审核通过';
                                else if($data['bord_status'] == 5) echo '审核未通过';
                                else if($data['bord_status'] == 7) echo '完成';
                                else if($data['bord_status'] == 9) echo '关闭';
                                else if($data['bord_status'] == 11) echo '物品已接收，符合条件';
                                else if($data['bord_status'] == 13) echo '物品已接收，不符合条件';
                                ?>
                            </td>
                            <td class="center"><?=date('Y-m-d', $data['bord_addtime'])?></td>
                            <td class="center">
                                <a href="/back/detail?bord_id=<?=$data['bord_id']?>" class="btn btn-mini btn-edit"><i class="icon-th-list"></i>详细</a>
                                <!--<button class="btn btn-mini btn-del"><i class="icon-trash"></i></button>-->
                            </td>
                        </tr>
                    <?php endforeach;?>
                <?php endif;?>
                </tbody>
            </table>
            <p>
<!--                <select id="batch-status" style="width: 120px;">
                    <option value="0">状态</option>
                    <option value="1">未审核</option>
                    <option value="3">审核通过</option>
                    <option value="5">审核未通过</option>
                    <option value="7">完成</option>
                    <option value="9">关闭</option>
                    <option value="11">物品已接收，符合条件</option>
                    <option value="13">物品已接收，不符合条件</option>
                </select>
                <button class="btn btn-mini" id="set-status">
                    <i class="icon-"></i>
                    设置
                </button>-->
<!--                <button class="btn btn-mini btn-primary" id="del-chk">
                    <i class="icon-trash"></i>
                    删除选中
                </button>-->
            <p><?php echo $page;?></p>
        </div>
    </div>
</div>
<script >
    seajs.config({
        base : "<?php echo $this->di['sysconfig']['staticServer'];?>js/",
        alias : {
            'chkAll' : 'utils/chkAll',
            'calendar' : 'utils/calendar'
        }
    });
    seajs.use("modules/back/main");
</script>
