<div class="page-header position-relative">
    <h1>
        商品属性管理
    </h1>
</div>
<div id = "yunduo-error-msg">

</div>
<div class="row-fluid">
    <div class="span12">
        <table class="table table-striped table-bordered table-hover" style="margin-bottom=10px;" id="sample-table-1">
            <thead>
                <tr>
                    <th class="center">   编号 </th>
                    <th>   属性名    </th>
                    <th>   排序    </th>
                    <th>   属性状态    </th>
                    <th >  添加时间    </th>
                    <th >  操作   </th>
                </tr>
            </thead>
            <tbody>
            <?php foreach ($attrs as $attr):?>
                <tr>
                    <td class='attr_id'><?=$attr['attrs_id']?></td>
                    <td><em  class='attr_name'><?=$attr['attrs_name']?></em></td>
                    <td><em  class='attr_rank'><?=$attr['attrs_rank']?></em></td>
                    <td class = "attr-status"><?=$attr['attrs_status']==1?'<span class="badge badge-success label-large">正常</span>':'<span class="badge badge-grey label-large">删除</span>'?></td>
                    <td><?=date('Y-m-d H:m:s', $attr['attrs_addtime'])?></td>
                    <td>
                    <?php if($attr['attrs_status'] == 1):?> <a href="javascript:void(0)"  class="btn btn-mini attr_add"><i class="icon-plus"></i>添加子属性</a><?php endif;?>
                      <a href="javascript:void(0)"  class="btn btn-mini attr_edit"><?=$attr['attrs_status'] == 1?'<i class="icon-pencil"></i>':'恢复此标签'?></a>
                      <?php if($attr['attrs_status'] == 1):?><a href="javascript:void(0)"  class="btn btn-mini attr_del"><i class="icon-trash"></i></a><?php endif;?>
                    </td>
                </tr>
                <?php if(!empty($attr['child'])){foreach ($attr['child'] as $val){?>
                <tr>
                    <td class='attr_id'><?=$val['attrs_id']?></td>
                    <td>└─<em  class='attr_name'><?=$val['attrs_name']?></em></td>
                    <td><em  class='attr_rank'><?=$val['attrs_rank']?></em></td>
                    <td class = "attr-status"><?=$val['attrs_status']==1?'<span class="badge badge-success label-large">正常</span>':'<span class="badge badge-grey label-large">删除</span>'?></td>
                    <td><?=date('Y-m-d H:m:s', $val['attrs_addtime'])?></td>
                    <td>
                      <a href="javascript:void(0)" class="btn btn-mini attr_edit"><?=$val['attrs_status'] == 1?'<i class="icon-pencil"></i>':'恢复此标签'?></a>
                      <?php if($val['attrs_status'] == 1):?><a href="javascript:void(0)"  class="btn btn-mini attr_del"><i class="icon-trash"></i></a><?php endif;?>
                    </td>
                </tr>
                <?php }} ?>
            <?php endforeach;?>
              <tr id="attr_add" style="<?php echo empty($attrs)?'':'display:none';?>">
                    <td>
                        <select id="pattr_id">
                            <option  value="0">顶级属性</option>
                        <?php foreach ($attrs as $attr):?>
                            <option  value="<?=$attr['attrs_id']?>"><?=$attr['attrs_name']?></option>
                        <?php endforeach;?>
                        </select>
                    </td>
                    <td><input type="text" value='' id="attr_name"/></td>
                    <td><input type="text" value='' id="attr_rank"/></td>
                    <td></td>
                    <td><a href="javascript:void(0)" id="attr_add_a" class="btn btn-mini">确定添加</a></td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
</div>
</div>
<script >
    seajs.use("<?php echo $this->di['sysconfig']['staticServer'];?>js/modules/attributs/main");
</script>

