  <div class="w auto">
    <!-- 公共面包屑开始 -->
    <div class="crumbs-nav"><a href="#">首页</a>
      <em>></em><a href="#">我的购物车</a>
    </div>
    <!-- 公共面包屑结束 -->
    <!-- 主体部分开始 -->
    <div class="content ovh">
      <!-- 正文部分开始 -->
      <div class="main full-wrap fl dib">
        <div class="info-tit rel">
          <h2 class="tit dib">我的购物车</h2>
          <span>（<em>0</em>/<em>50</em>）</span>
        </div>
        <div class="empty">
          <img src="<?php echo $this->di['sysconfig']['staticServer'];?>images/mall/empty-cart.jpg" alt="空购物车" class="empty-cart-img">
          <div class="dib vat">
            <p class="empty-desc">您的购物车中没有商品，<br>赶快挑选商品吧！</p>
            <p class="empty-btn tac"><a class="dib btn btn-blue" href="/">去商城逛逛</a></p>
          </div>
        </div>
      </div>
      <!-- 正文部分结束 -->
    </div>
    <!-- 主体部分结束 -->
  </div>