 <div class="w auto">
    <!-- 公共面包屑开始 -->
    <div class="crumbs-nav"><a href="#">首页</a>
      <em>></em><a href="#">我的购物车</a>
    </div>
    <!-- 公共面包屑结束 -->
    <!-- 主体部分开始 -->
    <div class="content ovh">
      <!-- 正文部分开始 -->
      <div class="main full-wrap fl dib">
        <div class="info-tit rel">
          <h2 class="tit dib">我的购物车</h2>
          <span>（<em><?=count($list)?></em>/<em>50</em>）</span>
        </div>
        <div class="my-cart-table">
          <table class="table cart-table-col-6">
            <thead>
              <tr>
                <th class="col-1">
                  <div class="bd-right"><input class="all-check vam" type="checkbox"/></div>
                </th>
                <th class="col-2">
                  <div class="bd-right">商品信息</div>
                </th>
                <th class="col-3">
                  <div class="bd-right">单价(元)</div>
                </th>
                <th class="col-4">
                  <div class="bd-right">数量</div>
                </th>
                <th class="col-5">
                  <div class="bd-right">小计(元)</div>
                </th>
                <th class="col-6">
                  操作
                </th>
              </tr>
            </thead>
            <tbody>
              <!-- 鼠标划过增加这个active的类 -->
              <!--<tr class="table-data">
                <td  class="col-1">
                  <input class="vam" type="checkbox">
                </td>
                 <td class="col-2 rel">
                  <img class="order-item-pic dib fl" src="<?php echo $this->di['sysconfig']['staticServer'];?>images/mall/shoes-example.jpg" alt="云朵智能童鞋">
                  <div class="order-item-desc dib">
                    <span class="order-item-name">云朵智能童鞋，XA1239481254</span>
                    <div class="change-box hover">
                      <p class="change-tit">修改</p>
                      <span class="order-item-info">颜色:黄色 尺码:32码</span>
                    </div>
                    <div class="change-detail">
                      <div class="change-para">
                        <dl>
                          <dt>尺码</dt>
                          <dd>
                            <span class="shoes-size-id size-cur" id="size-272" data="272">25</span>
                            <span class="shoes-size-id" id="size-274" data="274">26</span>
                            <span class="shoes-size-id" id="size-275" data="275">27</span>
                            <span class="shoes-size-id" id="size-276" data="276">28</span>
                            <span class="shoes-size-id" id="size-277" data="277">29</span>
                            <span class="shoes-size-id" id="size-278" data="278">30</span>
                            <span class="shoes-size-id" id="size-279" data="279">31</span>
                            <span class="shoes-size-id" id="size-280" data="280">32</span>
                            <span class="shoes-size-id" id="size-281" data="281">33</span>
                            <span class="shoes-size-id" id="size-282" data="282">34</span>
                            <span class="shoes-size-id disabled" id="size-273" data="273">35</span>
                          </dd>
                          <dt>颜色</dt>
                          <dd>
                            <img src="<?php echo $this->di['sysconfig']['staticServer'];?>images/mall/product/shoes-283.png" class="shoes-colors color-cur" alt="深海蓝" id="shoes-283">
                            <img src="<?php echo $this->di['sysconfig']['staticServer'];?>images/mall/product/shoes-284.png" class="shoes-colors" alt="冰雪粉" id="shoes-284">
                            <img src="<?php echo $this->di['sysconfig']['staticServer'];?>images/mall/product/shoes-285.png" class="shoes-colors" alt="云朵蓝" id="shoes-285">
                            <img src="<?php echo $this->di['sysconfig']['staticServer'];?>images/mall/product/shoes-286.png" class="shoes-colors" alt="荧光绿" id="shoes-286">
                            <img src="<?php echo $this->di['sysconfig']['staticServer'];?>images/mall/product/shoes-287.png" class="shoes-colors disabled" alt="糖果粉" id="shoes-287">
                          </dd>
                        </dl>
                        <div class="btn-row">
                          <input type="button" class="btn btn-blue btn-ensure bd-n" value="确定">
                          <a href="#" class="btn tdn btn-quit">取消</a>
                        </div>
                      </div>
                      <img class="cart-shoes-show" src="<?php echo $this->di['sysconfig']['staticServer'];?>images/mall/cart-shoes-show.jpg" alt="云朵智能童鞋">
                    </div>
                  </div>
                </td> 
                <td class="col-3">
                  199.00
                </td>
                <td class="col-4">
                  <div class="change-goods-num">
                    <a href="#" class="num-reduce dib" id="num-reduce"><i>-</i></a>
                    <input type="text" value="1" class="input-num">
                    <a href="#" class="num-add dib pressed" id="num-add"><i>+</i></a>
                  </div>
                </td>
                <td class="col-5">
                  199.00
                </td>
                <td class="col-6">
                  <div class="close">X</div>
                </td>
              </tr>-->

<!--               <tr class="table-data disabled">
                <td  class="col-1">
                  <span class="text-disabled">失效</span>
                </td>
                <td class="col-2">
                  <img class="order-item-pic dib fl" src="<?php echo $this->di['sysconfig']['staticServer'];?>images/mall/shoes-example.jpg" alt="云朵智能童鞋">
                  <div class="order-item-desc dib">
                    <span class="order-item-name">云朵智能童鞋，XA1239481254</span>
                    <span class="order-item-info">颜色:黄色 尺码:32码</span>
                  </div>
                </td>
                <td class="col-3">
                  199.00
                </td>
                <td class="col-4">
                  <div class="change-goods-num">
                    <a href="#" class="num-reduce dib" id="num-reduce"><i>-</i></a>
                    <input type="text" value="1" class="input-num">
                    <a href="#" class="num-add dib pressed" id="num-add"><i>+</i></a>
                  </div>
                </td>
                <td class="col-5">
                  199.00
                </td>
                <td class="col-6">
                  <div class="close">X</div>
                </td>
              </tr> -->
              <?php
                  $expired = 0;
                  foreach($list as $num => $cart):
                      $attrsName = explode(',', $cart['attrs_names']);
              ?>
              <tr class="table-data bd-n <?php echo $cart['goods_status'] == 1 ? '':'disabled'?>">
                <input type="hidden" class = "gid" data-id="<?=$cart['goods_id']?>" />
                <input type="hidden" class = "aid" data-id="<?=$cart['attrs_ids']?>" />
                <td  class="col-1">
                <?php if($cart['goods_status'] == 1):?>
                  <input class="vam" type="checkbox">
                <?php else:$expired++;?>
                  <span class="text-disabled">失效</span>
                <?php endif;?>
                </td>
                <td class="col-2">
                  <a href="/goods/index/<?=$cart['goods_id']?>" class="order-item-pic dib fl tac" target=_blank style="height:auto">
                    <img class="vam" style="width:90%" src="<?=$cart['goods_img']?>" alt="<?=$cart['attrs_names']?>">
                  </a>
                  <div class="order-item-desc dib">
                    <span class="order-item-name"><?=$cart['goods_name']?>,<?=$cart['barcode']?></span>
                    <span class="order-item-info">颜色:<?=$attrsName[0]?> 尺码:<?=$attrsName[1]?></span>
                  </div>
                </td>
                <td class="col-3">
                  <?=$cart['goods_price']?>
                </td>
                <td class="col-4"  style="vertical-align: top; padding-top: 40px;">
                  <div class="change-goods-num">
                    <a href="javascript:void(0)" class="num-reduce dib" class="num-reduce"><i>-</i></a>
                    <input type="text" readonly="readonly" value="<?=$cart['car_good_num']?>" class="input-num">
                    <a href="javascript:void(0)" class="num-add dib" class="num-add"><i>+</i></a>
                    <p class= "warn-stock dn" style="line-height:2.5;color:#d95453;font-size:12px">库存紧张</p>
                  </div>
                </td>
                <td class="col-5">
                  <?=sprintf("%.2f",$cart['goods_price']*$cart['car_good_num'])?>
                </td>
                <td class="col-6">
                  <div class="close">X</div>
                </td>
              </tr>
            <?php endforeach;?>
            </tbody>
            <tfoot>
              <tr>
                <th class="col-1">
                  <input class="all-check vam" type="checkbox">
                </th>
                <th colspan="5" class="tal">
                  <a href="javascript:void(0)" class="tb-del tdn" id="batch-del">删除</a>
                  <?php if($expired > 0):?>
                  <a href="javascript:void(0)" class="desc tdn" id="expired-del">清除失效宝贝</a>
                <?php endif;?>
                </th>
              </tr>
            </tfoot>
          </table>

          <div class="table-sum fix total">
            <div class="fr tar">
              <p><span class="tit">已选商品：</span><span class="desc"><i id="count-item">0</i>件</span></p>
              <p><span class="tit"></span>合计（不含运费）：<span class="desc fz24" id="total-p">0</span></p>
              <p class="btn-row"><input type="button" class="btn btn-blue bd-n" id="check-out" value="结算"></p>
            </div>
          </div>

        </div>
      </div>
      <!-- 正文部分结束 -->
    </div>
    <!-- 主体部分结束 -->
  </div>
<script>
    seajs.config({
        base : "<?php echo $this->di['sysconfig']['staticServer'];?>js/",
    });
    seajs.use("modules/front/cart/index");
</script>